using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class appsettings
	{
		public static void Apply()
		{
			GlobalVars.ConnectionStrings = XVar.Array();
			for(int i = 0; i < System.Configuration.ConfigurationManager.ConnectionStrings.Count; i++)
				GlobalVars.ConnectionStrings[System.Configuration.ConfigurationManager.ConnectionStrings[i].Name] = System.Configuration.ConfigurationManager.ConnectionStrings[i].ConnectionString;
			GlobalVars.dal_info = XVar.Array();
			GlobalVars.dal = new tDAL();
			GlobalVars.mlang_messages = XVar.Clone(XVar.Array());
			GlobalVars.mlang_charsets = XVar.Clone(XVar.Array());
			GlobalVars.mlang_defaultlang = XVar.Clone(CommonFunctions.getDefaultLanguage());
			GlobalVars.cCharset = new XVar("utf-8");
			GlobalVars.cCodepage = new XVar(65001);
			CommonFunctions.LoadLanguages();
			GlobalVars.dDebug = new XVar(false);
			GlobalVars.dSQL = new XVar("");
			GlobalVars.tables_data = XVar.Clone(XVar.Array());
			GlobalVars.page_layouts = XVar.Clone(XVar.Array());
			GlobalVars.field_labels = XVar.Clone(XVar.Array());
			GlobalVars.fieldToolTips = XVar.Clone(XVar.Array());
			GlobalVars.page_titles = XVar.Clone(XVar.Array());
			GlobalVars.placeHolders = XVar.Clone(XVar.Array());
			GlobalVars.breadcrumb_labels = XVar.Clone(XVar.Array());
			GlobalVars.lookupTableLinks = XVar.Clone(XVar.Array());
			GlobalVars._gmdays = XVar.Clone(new XVar(0, 31, 1, 31, 2, 28, 3, 31, 4, 30, 5, 31, 6, 30, 7, 31, 8, 31, 9, 30, 10, 31, 11, 30, 12, 31));
			GlobalVars.custom_labels = XVar.Clone(XVar.Array());
			GlobalVars.custom_labels.InitAndSetArrayItem(XVar.Array(), "English");
			GlobalVars.globalSettings = XVar.Clone(XVar.Array());
			GlobalVars.globalSettings.InitAndSetArrayItem(0, "nLoginForm");
			GlobalVars.globalSettings.InitAndSetArrayItem(1, "nLoginMethod");
			GlobalVars.twilioSID = new XVar("");
			GlobalVars.twilioAuth = new XVar("");
			GlobalVars.twilioNumber = new XVar("");
			GlobalVars.globalSettings.InitAndSetArrayItem(false, "bTwoFactorAuth");
			GlobalVars.globalSettings.InitAndSetArrayItem(XVar.Array(), "popupPagesLayoutNames");
									
	
			GlobalVars.globalSettings.InitAndSetArrayItem("login2", "popupPagesLayoutNames", "login");
			GlobalVars.globalSettings.InitAndSetArrayItem(false, "useBuiltInMailer");
			GlobalVars.globalSettings.InitAndSetArrayItem(false, "useCustomSMTPSettings");
			GlobalVars.globalSettings.InitAndSetArrayItem("", "strSMTPUser");
			GlobalVars.globalSettings.InitAndSetArrayItem("localhost", "strSMTPServer");
			GlobalVars.globalSettings.InitAndSetArrayItem("25", "strSMTPPort");
			GlobalVars.globalSettings.InitAndSetArrayItem("", "strSMTPPassword");
			GlobalVars.globalSettings.InitAndSetArrayItem("", "strFromEmail");
			GlobalVars.ajaxSearchStartsWith = new XVar(true);
			GlobalVars.globalSettings.InitAndSetArrayItem(1, "LandingPageType");
			GlobalVars.globalSettings.InitAndSetArrayItem("", "LandingTable");
			GlobalVars.globalSettings.InitAndSetArrayItem("login", "LandingPage");
			GlobalVars.globalSettings.InitAndSetArrayItem("login", "LandingURL");
			GlobalVars.globalSettings.InitAndSetArrayItem(XVar.Array(), "ProjectLogo");
			GlobalVars.globalSettings.InitAndSetArrayItem("ABCVote2016", "ProjectLogo", "English");
			GlobalVars.globalSettings.InitAndSetArrayItem(true, "createLoginPage");
			GlobalVars.globalSettings.InitAndSetArrayItem("", "apiGoogleMapsCode");
			GlobalVars.globalSettings.InitAndSetArrayItem(true, "printDetailTableName");
			GlobalVars.globalSettings.InitAndSetArrayItem("rrdf1", "dispFieldAlias");
			GlobalVars.globalSettings.InitAndSetArrayItem(true, "handleSearchSuggestInLookup");
			GlobalVars.globalSettings.InitAndSetArrayItem(40, "suggestStringSize");
			GlobalVars.globalSettings.InitAndSetArrayItem(10, "searchSuggestsNumber");
			GlobalVars.globalSettings.InitAndSetArrayItem(XVar.Array(), "override");
			GlobalVars.globalSettings.InitAndSetArrayItem(0, "mapProvider");
			GlobalVars.globalSettings.InitAndSetArrayItem(XVar.Array(), "CaptchaSettings");
			GlobalVars.globalSettings.InitAndSetArrayItem(0, "CaptchaSettings", "type");
			GlobalVars.globalSettings.InitAndSetArrayItem("", "CaptchaSettings", "siteKey");
			GlobalVars.globalSettings.InitAndSetArrayItem("", "CaptchaSettings", "secretKey");
			GlobalVars.globalSettings.InitAndSetArrayItem("5", "CaptchaSettings", "captchaPassesCount");
			GlobalVars.globalSettings.InitAndSetArrayItem(false, "CaptchaSettings", "isEnabledOnLogin");
			GlobalVars.globalSettings.InitAndSetArrayItem(false, "CaptchaSettings", "isEnabledOnRegister");
			GlobalVars.globalSettings.InitAndSetArrayItem(false, "CaptchaSettings", "isEnabledOnRemind");
			GlobalVars.wr_pagestylepath = new XVar("AvenueAvenue");
			GlobalVars.wr_is_standalone = new XVar(false);
			GlobalVars.WRAdminPagePassword = new XVar("");
			GlobalVars.cLoginTable = new XVar("dbo._ABCSecurity");
			GlobalVars.cDisplayNameField = new XVar("username");
			GlobalVars.cUserNameField = new XVar("username");
			GlobalVars.cPasswordField = new XVar("password");
			GlobalVars.cUserGroupField = new XVar("role");
			GlobalVars.cEmailField = new XVar("");
			if(GlobalVars.cDisplayNameField == XVar.Pack(""))
			{
				GlobalVars.cDisplayNameField = XVar.Clone(GlobalVars.cUserNameField);
			}
			GlobalVars.cDisplayNameFieldType = new XVar(200);
			GlobalVars.cUserNameFieldType = new XVar(200);
			GlobalVars.cPasswordFieldType = new XVar(200);
			GlobalVars.cEmailFieldType = new XVar(200);
			GlobalVars.useAJAX = new XVar(true);
			GlobalVars.suggestAllContent = new XVar(true);
			GlobalVars.strLastSQL = new XVar("");
			GlobalVars.showCustomMarkerOnPrint = new XVar(false);
			GlobalVars.menuAssignments = XVar.Clone(XVar.Array());
			GlobalVars.menuSelector = XVar.Clone(XVar.Array());
			GlobalVars.menuSelector.InitAndSetArrayItem("welcome_page", "page");
			GlobalVars.menuSelector.InitAndSetArrayItem("mainmenu", "id");
			GlobalVars.menuSelector.InitAndSetArrayItem("welcome_page", "name");
			GlobalVars.menuSelector.InitAndSetArrayItem("0", "horizontal");
			GlobalVars.menuAssignments.InitAndSetArrayItem(GlobalVars.menuSelector, null);
			GlobalVars.menuSelector = XVar.Clone(XVar.Array());
			GlobalVars.menuSelector.InitAndSetArrayItem("welcome_page", "page");
			GlobalVars.menuSelector.InitAndSetArrayItem("welcome_page", "id");
			GlobalVars.menuSelector.InitAndSetArrayItem("welcome_page", "name");
			GlobalVars.menuSelector.InitAndSetArrayItem("0", "horizontal");
			GlobalVars.menuAssignments.InitAndSetArrayItem(GlobalVars.menuSelector, null);
			GlobalVars.menuStyles = XVar.Clone(XVar.Array());
			GlobalVars.menuTreelikeFlags = XVar.Clone(XVar.Array());
			GlobalVars.menuTreelikeFlags.InitAndSetArrayItem(0, "main");
			GlobalVars.menuDrillDownFlags = XVar.Clone(XVar.Array());
			GlobalVars.menuDrillDownFlags.InitAndSetArrayItem(0, "main");
			GlobalVars.menuTreelikeFlags.InitAndSetArrayItem(0, "welcome_page");
			GlobalVars.menuDrillDownFlags.InitAndSetArrayItem(0, "welcome_page");
			GlobalVars.tableCaptions = XVar.Clone(XVar.Array());
			GlobalVars.tableCaptions.InitAndSetArrayItem(XVar.Array(), "English");
			GlobalVars.tableCaptions.InitAndSetArrayItem("", "English", "");
			GlobalVars.tableCaptions.InitAndSetArrayItem("ABCReports", "English", "dbo__ABCReports");
			GlobalVars.tableCaptions.InitAndSetArrayItem("ABCVotes", "English", "dbo__ABCVotes");
			GlobalVars.tableCaptions.InitAndSetArrayItem("", "English", "");
			GlobalVars.tableCaptions.InitAndSetArrayItem("ABCSecurity", "English", "dbo__ABCSecurity");
			GlobalVars.tableCaptions.InitAndSetArrayItem("ABC Voting Submitted", "English", "ABC_Voting_Submitted");
			GlobalVars.tableCaptions.InitAndSetArrayItem("ABC Voting Recirculated", "English", "ABC_Voting_Recirculated");
			GlobalVars.tableCaptions.InitAndSetArrayItem("ABC Voting My Voting", "English", "ABC_Voting_My_Voting");
			GlobalVars.tableCaptions.InitAndSetArrayItem("ABC Voting Batch Create", "English", "ABC_Voting_Batch_Create");
			GlobalVars.tableCaptions.InitAndSetArrayItem("Vw ABCReports Vote Count", "English", "dbo_vwABCReportsVoteCount");
			GlobalVars.tableCaptions.InitAndSetArrayItem(XVar.Array(), "");
			GlobalVars.tableCaptions.InitAndSetArrayItem("", "", "");
			GlobalVars.tableCaptions.InitAndSetArrayItem("ABCReports", "", "dbo__ABCReports");
			GlobalVars.globalEvents = XVar.Clone(new class_GlobalEvents());
			GlobalVars.tableEvents = XVar.Clone(XVar.Array());
			GlobalVars.dalTables = XVar.Clone(XVar.Array());
			GlobalVars.tableinfo_cache = XVar.Clone(XVar.Array());
			GlobalVars.contextStack = XVar.Clone(new RunnerContext());
			GlobalVars.cman = XVar.Clone(new ConnectionManager());
			GlobalVars.currentConnection = new XVar(null);
			GlobalVars.page_titles.InitAndSetArrayItem(XVar.Array(), ".global");
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
			}
			if(CommonFunctions.mlang_getcurrentlang() == "")
			{
			}
			GlobalVars.globalSettings.InitAndSetArrayItem(true, "showDetailedError");
			GlobalVars._cachedSeachClauses = XVar.Clone(XVar.Array());
			GlobalVars.conn = XVar.Clone(GlobalVars.cman.getDefault().conn);
			GlobalVars.logoutPerformed = new XVar(false);
			GlobalVars.scriptname = XVar.Clone(MVCFunctions.getFileNameFromURL());
			if((XVar)((XVar)((XVar)((XVar)(!(XVar)(CommonFunctions.isLogged()))  && (XVar)(GlobalVars.scriptname != "login"))  && (XVar)(GlobalVars.scriptname != "remind"))  && (XVar)(GlobalVars.scriptname != "register"))  && (XVar)(GlobalVars.scriptname != "checkduplicates"))
			{
				Security.doGuestLogin();
			}
			GlobalVars.isGroupSecurity = new XVar(true);
			GlobalVars.isUseRTEBasic = new XVar(true);
			GlobalVars.isUseRTECK = new XVar(false);
			GlobalVars.isUseRTEInnova = new XVar(false);
			GlobalVars.caseInsensitiveUsername = new XVar(0);
			GlobalVars.menuNodesIndex = new XVar(0);
			GlobalVars.pagesData = XVar.Clone(XVar.Array());

			// initializations from other files

			GlobalVars.bSubqueriesSupported = new XVar(true);
			GlobalVars.cMySQLNames = new XVar("");
			GlobalVars.cache_db2time = XVar.Clone(XVar.Array());
			GlobalVars.cache_formatweekstart = XVar.Clone(XVar.Array());
			GlobalVars.cache_fullfieldname = XVar.Clone(XVar.Array());
			GlobalVars.cache_getdayofweek = XVar.Clone(XVar.Array());
			GlobalVars.cache_getweekstart = XVar.Clone(XVar.Array());
			GlobalVars.dal = XVar.Clone(new tDAL());
			GlobalVars.dal_info = XVar.Clone(XVar.Array());
			GlobalVars.db_query_safe_err = new XVar(false);
			GlobalVars.db_query_safe_errstr = new XVar("");
			GlobalVars.gLoadSearchControls = new XVar(30);

			GlobalVars.g_defaultOptionValues = new XVar();
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "add");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "addMultistep");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "Absolute");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(".+$", "acceptFileTypes");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "addFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "addPageEvents");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "ajaxCodeSnippetAdded");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "advSearchFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(1, "afterAddAction");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "afterAddActionDetTable");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(1, "afterEditAction");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "afterEditActionDetTable");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "AllowToAdd");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "allowFieldsReordering");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "allowShowHideFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "allSearchFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "arrGroupsPerPage");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "arrKeyFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "arrAddTabs");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "arrEditTabs");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "arrGridTabs");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "arrRecsPerPage");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "arrRegisterTabs");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "arrViewTabs");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "audioTitleField");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "audit");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "autoCompleteFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "autoCompleteFieldsAdd");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "autoCompleteFieldsEdit");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "autoCompleteFieldsOnEdit");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "AutoInc");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "autoUpload");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "autoUpdatable");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "bAddPage");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "bAdvancedSearch");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "badgeColor");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "bEditPage");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "bExportPage");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "bInlineAdd");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "bInlineEdit");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "bUpdateSelected");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "bIsEncrypted");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "bListPage");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "bPrinterPage");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "bViewPage");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "buttonsAdded");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("captcha", "captchaAddFieldName");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("captcha", "captchaEditFieldName");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "CompatibilityMode");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "categoryFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(60, "ChartRefreshTime");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "chartXml");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "chartType");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "closePopupAfterAdd");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "closePopupAfterEdit");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(160, "controlWidth");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "copy");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "CreateThumbnail");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "createSortByDropdown");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "crossTabReport");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "CustomDisplay");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(Constants.DL_SINGLE, "detailsLinksOnList");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "dashElements");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "dashCells");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "DateEditType");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "DecimalDigits");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "defaultSearchOption");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "DefaultValue");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "delete");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "DeleteAssociatedFile");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "denyDuplicates");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "DependentLookups");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "dependentFilterName");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "dependentFilters");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "descendingOrder");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "DisplayField");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "edit");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "editMultistep");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "editFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "EditFormat");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "EditParams");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "exportTo");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(Constants.EXPORT_BOTH, "exportFormatting");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(",", "exportDelimiter");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "fieldIsVideoUrl");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "fieldIsImageUrl");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "FieldType");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "FieldPermissions");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "fieldsForRegister");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "Filename");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "filterFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(Constants.FF_VALUE_LIST, "filterFormat");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "filterIntervals");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(Constants.FT_NONE, "filterTotals");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(Constants.FM_NONE, "filterMultiSelect");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "filterCheckedMessageText");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "filterCheckedMessageType");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "filterUncheckedMessageText");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "filterUncheckedMessageType");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(1, "filterSliderStepType");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(1, "filterSliderStepValue");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "filterKnobsType");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "filterApplyBtn");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "flexibleSearch");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "FormatTimeAttrs");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "freeInput");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "FullName");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "fieldEvents");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "fieldViewEvents");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "googleLikeFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "GoodName");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "hasDependentFilter");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "hasEncryptedFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "hideEmptyFieldsOnView");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "HorizontalLookup");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "hlNewWindow");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "hlType");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "hlLinkWordNameType");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "hlLinkWordText");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "hlTitleField");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "highlightSearchResults");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("text", "HTML5InuptType");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "Index");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(100, "InitialYearFactor");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "ImageHeight");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "ImageWidth");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "import");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "inlineAdd");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "inlineAddFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "inlineEdit");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "updateSelected");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "inlineEditFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "isDisplayLoading");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "tableType");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "IsRequired");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "isResizeColumns");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "isSeparate");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "UpdateLatLng");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "isUseAjaxSuggest");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "isUseAudio");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "isUseFieldsMaps");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "isUseMainMaps");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "isUseTimeForSearch");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "isUseToolTips");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "isUseVideo");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "listGridLayout");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "isExistTotalFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "isTotalMin");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "isTotalAvg");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "isTotalMax");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "isTotalSum");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(1, "isViewPagePDFFitToPage");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(1, "isPrinterPagePDFFitToPage");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "isLandscapeViewPDFOrientation");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "isLandscapePrinterPagePDFOrientation");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "isPrinterPagePDF");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "isViewPagePDF");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "isSQLExpression");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(1, "isPrinterPageFitToPage");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "isCaptchaEnabledOnAdd");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "isCaptchaEnabledOnEdit");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "Keys");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "Label");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "LookupConnId");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(10, "LastYearFactor");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(Constants.LCT_DROPDOWN, "LCType");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "LinkField");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "LinkFieldType");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "LinkPrefix");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "list");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "listAjax");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "listFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "locking");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "LookupDesc");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "LookupOrderBy");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "LookupTable");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "LookupType");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "LookupUnique");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "LookupValues");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "LookupWhere");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "LookupWhereCode");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "mainTableOwnerID");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "mapData");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "masterListFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(null, "maxFileSize");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(null, "maxImageHeight");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(null, "maxImageWidth");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(1, "maxNumberOfFiles");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(null, "maxTotalFilesSize");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "moveNext");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "Multiselect");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "NCSearch");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "NeedEncode");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "NewSize");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "noRecordsFirstPage");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(Constants.ADVSECURITY_NONE, "nSecOptions");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "NumberOfChars");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(10, "numberOfVisibleItems");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(100, "nViewPagePDFScale");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(100, "nPrinterPagePDFScale");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(100, "nPrinterPageScale");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "nPrinterPDFSplitRecords");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "nPrinterSplitRecords");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "OriginalTable");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "orderindexes");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "OwnerID");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "ownerTable");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "OraSequenceName");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "pageSize");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "panelSearchFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "parentFilterField");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "parentFilters");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "printFriendly");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "printFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "popupPagesLayoutNames");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "printGridLayout");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "printReportLayout");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "printerPageOrientation");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "recsLimit");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(1, "recsPerRowList");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(1, "recsPerRowPrint");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "registerMultistep");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "reportGroupFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "reportGroupFieldsData");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "reportHorizontalSummary");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "reportVerticalSummary");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "reportPageSummary");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "reportGlobalSummary");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "repShowDet");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "ResizeImage");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "RewindEnabled");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "rowHighlite");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "requiredSearchFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "reportPrintPartitionType");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(3, "reportPrintGroupsPerPage");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "reportPrintPDFGroupsPerPage");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "reorderRecordsByHeader");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "searchFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "searchSaving");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "searchPanelOptions");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(1, "SelectSize");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "selectExportDelimiter");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "selectExportFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "searchIsRequiredForFilters");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "searchOptionsList");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "ShortName");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "shortTableName");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "showAddInPopup");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "ShowCustomExpr");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "showEditInPopup");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "ShowFileSize");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "ShowIcon");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "showSearchPanel");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "showSimpleSearchOptions");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "ShowThumbnail");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "ShowTime");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "showViewInPopup");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "showCollapsed");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "showWithNoRecords");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "SimpleAdd");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "ShowListOfThumbnails");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(Constants.SORT_BY_DISP_VALUE, "sortValueType");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "sqlFrom");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "sqlHead");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "sqlTail");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "sqlWhereExpr");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(null, "sqlquery");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "strField");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "strFilename");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "strName");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "strOrderBy");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "StrThumbnail");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "strSortControlSettingsJSON");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "strClickActionJSON");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(0, "ThumbnailSize");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "scrollGridBody");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "showGroupSummaryCount");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "totalsFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(72, "ThumbHeight");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(72, "ThumbWidth");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "truncateText");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "UploadFolder");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "UploadCodeExpression");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "UseCategory");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "UseRTE");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "UseTimestamp");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "validateAs");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(200, "videoHeight");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(300, "videoWidth");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "videoTitleField");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "view");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem("", "ViewFormat");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(XVar.Array(), "viewFields");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "viewMultistep");
			GlobalVars.g_defaultOptionValues.InitAndSetArrayItem(false, "warnLeavingPages");

			GlobalVars.g_settingsType = new XVar();
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "Absolute");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "acceptFileTypes");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "AllowToAdd");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "autoCompleteFields");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "autoCompleteFieldsOnEdit");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "AutoInc");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "audioTitleField");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "autoUpload");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "autoUpdatable");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "bAddPage");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "bAdvancedSearch");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "bEditPage");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "bExportPage");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "bInlineAdd");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "bInlineEdit");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "bUpdateSelected");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "bIsEncrypted");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "bListPage");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "bPrinterPage");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "bViewPage");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "CompatibilityMode");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "categoryFields");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "controlWidth");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "CreateThumbnail");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "CustomDisplay");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "DateEditType");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "DecimalDigits");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "DeleteAssociatedFile");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "denyDuplicates");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "DependentLookups");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "DisplayField");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "EditFormat");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "EditParams");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "fieldIsVideoUrl");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "fieldIsImageUrl");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "FieldType");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "FieldPermissions");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "Filename");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "FormatTimeAttrs");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "freeInput");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "FullName");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "fieldEvents");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "fieldViewEvents");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "GoodName");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "HorizontalLookup");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "hlNewWindow");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "hlType");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "hlLinkWordNameType");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "hlLinkWordText");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "hlTitleField");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "HTML5InuptType");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "Index");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "InitialYearFactor");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "ImageHeight");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "ImageWidth");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "IsRequired");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "isSeparate");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "UpdateLatLng");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "Label");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "LastYearFactor");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "LCType");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "LinkField");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "LinkFieldType");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "LinkPrefix");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "LookupConnId");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "LookupDesc");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "LookupOrderBy");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "LookupTable");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "LookupType");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "LookupUnique");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "LookupValues");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "LookupWhere");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "LookupWhereCode");
			GlobalVars.g_settingsType.InitAndSetArrayItem(1, "lowGroup");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "mapData");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "maxFileSize");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "maxImageHeight");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "maxImageWidth");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "maxNumberOfFiles");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "maxTotalFilesSize");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "Multiselect");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "nCols");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "NeedEncode");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "NewSize");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "nRows");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.ADVSECURITY_NONE, "nSecOptions");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "ownerTable");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "OraSequenceName");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "ResizeImage");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "RewindEnabled");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "SelectSize");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "ShowCustomExpr");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "ShowFileSize");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "ShowIcon");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "ShowThumbnail");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "ShowTime");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "SimpleAdd");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "ShowListOfThumbnails");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "strField");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "strFilename");
			GlobalVars.g_settingsType.InitAndSetArrayItem("", "filterTotalFields");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "strEditMask");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "strName");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "StrThumbnail");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "ThumbnailSize");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "ThumbHeight");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "ThumbWidth");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "UploadFolder");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_GLOBAL, "UploadCodeExpression");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "UseCategory");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "UseRTE");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "UseTimestamp");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_EDIT, "validateAs");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "videoHeight");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "videoWidth");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "videoTitleField");
			GlobalVars.g_settingsType.InitAndSetArrayItem(Constants.SETTING_TYPE_VIEW, "ViewFormat");
			GlobalVars.group_sort_y = XVar.Clone(XVar.Array());
			GlobalVars.mbEnabled = XVar.Clone(MVCFunctions.extension_loaded(new XVar("mbstring")));
			GlobalVars.menuNodesObject = new XVar(null);
			GlobalVars.pageTypesForEdit = XVar.Clone(XVar.Array());
			GlobalVars.pageTypesForEdit.InitAndSetArrayItem("add", null);
			GlobalVars.pageTypesForEdit.InitAndSetArrayItem("edit", null);
			GlobalVars.pageTypesForEdit.InitAndSetArrayItem("search", null);
			GlobalVars.pageTypesForEdit.InitAndSetArrayItem("register", null);
			GlobalVars.pageTypesForView = XVar.Clone(XVar.Array());
			GlobalVars.pageTypesForView.InitAndSetArrayItem("list", null);
			GlobalVars.pageTypesForView.InitAndSetArrayItem("view", null);
			GlobalVars.pageTypesForView.InitAndSetArrayItem("export", null);
			GlobalVars.pageTypesForView.InitAndSetArrayItem("print", null);
			GlobalVars.pageTypesForView.InitAndSetArrayItem("report", null);
			GlobalVars.pageTypesForView.InitAndSetArrayItem("rprint", null);
			GlobalVars.pageTypesForView.InitAndSetArrayItem("chart", null);
			GlobalVars.print_r_depth = new XVar(0);
			GlobalVars.projectEntities = XVar.Clone(XVar.Array());
			GlobalVars.projectEntitiesReverse = XVar.Clone(XVar.Array());
			GlobalVars.projectPath = new XVar("");
			GlobalVars.tablesByGoodName = XVar.Clone(XVar.Array());
			GlobalVars.tablesByUpperCase = XVar.Clone(XVar.Array());
			GlobalVars.tablesByUpperGoodname = XVar.Clone(XVar.Array());
			GlobalVars.useOldMysqlLib = XVar.Clone(0 != 0);
							GlobalVars.useUTF8 = true;
			GlobalVars.masterTablesData = XVar.Array();
			GlobalVars.detailsTablesData = XVar.Array();
			GlobalVars.BufferStack = new Stack<StringBuilder>();
			MVCFunctions.ob_start();
			GlobalVars.IsOutputDone = false;
			CommonFunctions.InitLocale();
		}
	}

	public static partial class Constants
	{
		public const string NOT_TABLE_BASED_TNAME = ".global";
		public const string PAGE_LIST = "list";
		public const string PAGE_MASTER_INFO_LIST = "masterlist";
		public const string PAGE_ADD = "add";
		public const string PAGE_EDIT = "edit";
		public const string PAGE_VIEW = "view";
		public const string PAGE_MENU = "menu";
		public const string PAGE_LOGIN = "login";
		public const string PAGE_REGISTER = "register";
		public const string PAGE_REMIND = "remind";
		public const string PAGE_CHANGEPASS = "changepwd";
		public const string PAGE_SEARCH = "search";
		public const string PAGE_REPORT = "report";
		public const string PAGE_MASTER_INFO_REPORT = "masterreport";
		public const string PAGE_CHART = "chart";
		public const string PAGE_PRINT = "print";
		public const string PAGE_MASTER_INFO_PRINT = "masterprint";
		public const string PAGE_RPRINT = "rprint";
		public const string PAGE_MASTER_INFO_RPRINT = "masterrprint";
		public const string PAGE_EXPORT = "export";
		public const string PAGE_IMPORT = "import";
		public const string PAGE_ADMIN_MEMBERS = "admin_members";
		public const string PAGE_ADMIN_RIGHTS = "admin_rights";
		public const string PAGE_INLINEADD = "inlineadd";
		public const string PAGE_INLINEEDIT = "inlineedit";
		public const string PAGE_DASHBOARD = "dashboard";
		public const string PAGE_DASHMAP = "map";
		public const string ADMIN_USERS = "admin_users";
		public const string FORMAT_VIEW = "ViewFormats";
		public const string FORMAT_EDIT = "EditFormats";
		public const string FORMAT_NONE = "";
		public const string FORMAT_DATE_SHORT = "Short Date";
		public const string FORMAT_DATE_LONG = "Long Date";
		public const string FORMAT_DATE_TIME = "Datetime";
		public const string FORMAT_TIME = "Time";
		public const string FORMAT_CURRENCY = "Currency";
		public const string FORMAT_PERCENT = "Percent";
		public const string FORMAT_HYPERLINK = "Hyperlink";
		public const string FORMAT_EMAILHYPERLINK = "Email Hyperlink";
		public const string FORMAT_FILE_IMAGE = "File-based Image";
		public const string FORMAT_FILE_IMAGE_OLD = "Old file-based Image";
		public const string FORMAT_DATABASE_IMAGE = "Database Image";
		public const string FORMAT_DATABASE_FILE = "Database File";
		public const string FORMAT_FILE = "Document Download";
		public const string FORMAT_LOOKUP_WIZARD = "Lookup wizard";
		public const string FORMAT_PHONE_NUMBER = "Phone Number";
		public const string FORMAT_NUMBER = "Number";
		public const string FORMAT_HTML = "HTML";
		public const string FORMAT_CHECKBOX = "Checkbox";
		public const string FORMAT_MAP = "Map";
		public const string FORMAT_CUSTOM = "Custom";
		public const string FORMAT_AUDIO = "Audio file";
		public const string FORMAT_DATABASE_AUDIO = "Database audio";
		public const string FORMAT_VIDEO = "Video file";
		public const string FORMAT_VIDEO_HTML5 = "Video file HTML5";
		public const string FORMAT_DATABASE_VIDEO = "Database video";
		public const string EDIT_FORMAT_NONE = "";
		public const string EDIT_FORMAT_TEXT_FIELD = "Text field";
		public const string EDIT_FORMAT_TEXT_AREA = "Text area";
		public const string EDIT_FORMAT_PASSWORD = "Password";
		public const string EDIT_FORMAT_DATE = "Date";
		public const string EDIT_FORMAT_TIME = "Time";
		public const string EDIT_FORMAT_RADIO = "Radio button";
		public const string EDIT_FORMAT_CHECKBOX = "Checkbox";
		public const string EDIT_FORMAT_DATABASE_IMAGE = "Database image";
		public const string EDIT_FORMAT_DATABASE_FILE = "Database file";
		public const string EDIT_FORMAT_FILE = "Document upload";
		public const string EDIT_FORMAT_LOOKUP_WIZARD = "Lookup wizard";
		public const string EDIT_FORMAT_HIDDEN = "Hidden field";
		public const string EDIT_FORMAT_READONLY = "Readonly";
		public const int EDIT_DATE_SIMPLE = 0;
		public const int EDIT_DATE_SIMPLE_INLINE = 2;
		public const int EDIT_DATE_SIMPLE_DP = 11;
		public const int EDIT_DATE_DD = 12;
		public const int EDIT_DATE_DD_INLINE = 5;
		public const int EDIT_DATE_DD_DP = 13;
		public const int MODE_ADD = 0;
		public const int MODE_EDIT = 1;
		public const int MODE_SEARCH = 2;
		public const int MODE_LIST = 3;
		public const int MODE_PRINT = 4;
		public const int MODE_VIEW = 5;
		public const int MODE_INLINE_ADD = 6;
		public const int MODE_INLINE_EDIT = 7;
		public const int MODE_EXPORT = 8;
		public const int LOGIN_HARDCODED = 0;
		public const int LOGIN_TABLE = 1;
		public const int SECURITY_NONE = -1;
		public const int SECURITY_HARDCODED = 0;
		public const int SECURITY_TABLE = 1;
		public const int SECURITY_AD = 2;
		public const int ADVSECURITY_ALL = 0;
		public const int ADVSECURITY_VIEW_OWN = 1;
		public const int ADVSECURITY_EDIT_OWN = 2;
		public const int ADVSECURITY_NONE = 3;
		public const string ACCESS_LEVEL_ADMIN = "Admin";
		public const string ACCESS_LEVEL_ADMINGROUP = "AdminGroup";
		public const string ACCESS_LEVEL_USER = "User";
		public const string ACCESS_LEVEL_GUEST = "Guest";
		public const int nDATABASE_MySQL = 0;
		public const int nDATABASE_Oracle = 1;
		public const int nDATABASE_MSSQLServer = 2;
		public const int nDATABASE_Access = 3;
		public const int nDATABASE_PostgreSQL = 4;
		public const int nDATABASE_Informix = 5;
		public const int nDATABASE_SQLite3 = 6;
		public const int nDATABASE_DB2 = 7;
		public const int nDATABASE_Interbase = 16;
		public const int ADD_SIMPLE = 0;
		public const int ADD_INLINE = 1;
		public const int ADD_ONTHEFLY = 2;
		public const int ADD_MASTER = 3;
		public const int ADD_POPUP = 4;
		public const int ADD_DASHBOARD = 5;
		public const int ADD_MASTER_POPUP = 6;
		public const int ADD_MASTER_DASH = 7;
		public const int EDIT_SIMPLE = 0;
		public const int EDIT_INLINE = 1;
		public const int EDIT_POPUP = 3;
		public const int EDIT_DASHBOARD = 4;
		public const int EDIT_SELECTED_SIMPLE = 5;
		public const int EDIT_SELECTED_POPUP = 6;
		public const int VIEW_SIMPLE = 0;
		public const int VIEW_POPUP = 1;
		public const int VIEW_DASHBOARD = 2;
		public const int LOGIN_SIMPLE = 0;
		public const int LOGIN_POPUP = 1;
		public const int LOGIN_EMBEDED = 2;
		public const int REGISTER_SIMPLE = 0;
		public const int REGISTER_POPUP = 1;
		public const int REMIND_SIMPLE = 0;
		public const int REMIND_POPUP = 1;
		public const int EXPORT_SIMPLE = 0;
		public const int EXPORT_POPUP = 1;
		public const int EXPORT_RAW = 0;
		public const int EXPORT_FORMATTED = 1;
		public const int EXPORT_BOTH = 2;
		public const int titTABLE = 0;
		public const int titVIEW = 1;
		public const int titREPORT = 2;
		public const int titCHART = 3;
		public const int titDASHBOARD = 4;
		public const int TAB_TYPE_TAB = 0;
		public const int TAB_TYPE_SECTION = 1;
		public const int TAB_TYPE_STEP = 2;
		public const int REPORT_STEPPED = 0;
		public const int REPORT_BLOCK = 1;
		public const int REPORT_OUTLINE = 2;
		public const int REPORT_ALIGN = 3;
		public const int REPORT_TABULAR = 6;
		public const int TOTAL_NONE = -1;
		public const int TOTAL_MAX = 0;
		public const int TOTAL_AVG = 1;
		public const int TOTAL_SUM = 3;
		public const int TOTAL_MIN = 4;
		public const int LIST_SIMPLE = 0;
		public const int LIST_LOOKUP = 1;
		public const int LIST_DETAILS = 3;
		public const int LIST_AJAX = 4;
		public const int RIGHTS_PAGE = 5;
		public const int MEMBERS_PAGE = 6;
		public const int LIST_DASHBOARD = 7;
		public const int LIST_DASHDETAILS = 8;
		public const int MAP_DASHBOARD = 9;
		public const int LIST_MASTER = 10;
		public const int PRINT_MASTER = 11;
		public const int REPORT_SIMPLE = 0;
		public const int REPORT_POPUPDETAILS = 1;
		public const int REPORT_DASHBOARD = 2;
		public const int REPORT_DETAILS = 3;
		public const int REPORT_DASHDETAILS = 4;
		public const int CHART_SIMPLE = 0;
		public const int CHART_POPUPDETAILS = 1;
		public const int CHART_DASHBOARD = 2;
		public const int CHART_DETAILS = 3;
		public const int CHART_DASHDETAILS = 4;
		public const int DP_POPUP = 0;
		public const int DP_INLINE = 1;
		public const int DP_NONE = 2;
		public const int DL_SINGLE = 0;
		public const int DL_INDIVIDUAL = 1;
		public const int DL_NONE = 2;
		public const int SEARCH_SIMPLE = 0;
		public const int SEARCH_LOAD_CONTROL = 1;
		public const int SEARCH_DASHBOARD = 2;
		public const int LCT_DROPDOWN = 0;
		public const int LCT_AJAX = 1;
		public const int LCT_LIST = 2;
		public const int LCT_CBLIST = 3;
		public const int LCT_RADIO = 4;
		public const int LT_LISTOFVALUES = 0;
		public const int LT_LOOKUPTABLE = 1;
		public const int LT_QUERY = 2;
		public const int ENCRYPTION_NONE = 0;
		public const int ENCRYPTION_DB = 1;
		public const int ENCRYPTION_PHP = 2;
		public const int ENCRYPTION_ALG_DES = 1;
		public const int ENCRYPTION_ALG_AES = 128;
		public const string SETTING_TYPE_GLOBAL = "global";
		public const string SETTING_TYPE_VIEW = "view";
		public const string SETTING_TYPE_EDIT = "edit";
		public const int otNone = 0;
		public const int otUseMobile = 1;
		public const int otUseDesktop = 2;
		public const string CONTAINS = "Contains";
		public const string EQUALS = "Equals";
		public const string STARTS_WITH = "Starts with";
		public const string MORE_THAN = "More than";
		public const string LESS_THAN = "Less than";
		public const string BETWEEN = "Between";
		public const string EMPTY_SEARCH = "Empty";
		public const string NOT_CONTAINS = "NOT Contains";
		public const string NOT_EQUALS = "NOT Equals";
		public const string NOT_STARTS_WITH = "NOT Starts with";
		public const string NOT_MORE_THAN = "NOT More than";
		public const string NOT_LESS_THAN = "NOT Less than";
		public const string NOT_BETWEEN = "NOT Between";
		public const string NOT_EMPTY = "NOT Empty";
		public const int SEARCHID_SIMPLE = 1;
		public const int SEARCHID_PANEL = 10;
		public const int SEARCHID_ALL = 10000;
		public const int FT_NONE = 0;
		public const int FT_COUNT = 1;
		public const int FT_MIN = 2;
		public const int FT_MAX = 3;
		public const int FM_NONE = 0;
		public const int FM_ON_DEMAND = 1;
		public const int FM_ALWAYS = 2;
		public const string FF_VALUE_LIST = "Values list";
		public const string FF_BOOLEAN = "Options list";
		public const string FF_INTERVAL_LIST = "Interval list";
		public const string FF_INTERVAL_SLIDER = "Interval slider";
		public const int FIL_NONE = 0;
		public const int FIL_MORE_THAN = 1;
		public const int FIL_LESS_THAN = 1;
		public const int FIL_LESS_THAN_OR_EQUAL = 2;
		public const int FIL_MORE_THAN_OR_EQUAL = 2;
		public const int FIL_REMAINDER = 3;
		public const int FS_BOTH = 0;
		public const int FS_MIN_ONLY = 1;
		public const int FS_MAX_ONLY = 2;
		public const int FSST_SECONDS = 0;
		public const int FSST_MINUTES = 1;
		public const int FSST_HOURS = 2;
		public const int FSST_DAYS = 3;
		public const int FSST_MONTHS = 4;
		public const int FSST_YEARS = 5;
		public const int SORT_BY_DISP_VALUE = 0;
		public const int SORT_BY_DB_VALUE = 1;
		public const int SORT_BY_GR_VALUE = 2;
		public const int gltHORIZONTAL = 0;
		public const int gltVERTICAL = 1;
		public const int gltCOLUMNS = 2;
		public const int gltFLEXIBLE = 3;
		public const int DESKTOP = 1;
		public const int TABLET_10_IN = 2;
		public const int TABLET_7_IN = 3;
		public const int SMARTPHONE_LANDSCAPE = 4;
		public const int SMARTPHONE_PORTRAIT = 5;
		public const int DASHBOARD_LIST = 0;
		public const int DASHBOARD_CHART = 1;
		public const int DASHBOARD_REPORT = 2;
		public const int DASHBOARD_RECORD = 3;
		public const int DASHBOARD_SEARCH = 4;
		public const int DASHBOARD_DETAILS = 5;
		public const int DASHBOARD_MAP = 6;
		public const int DASHBOARD_SNIPPET = 7;
		public const int MESSAGE_INFO = 1;
		public const int MESSAGE_ERROR = 2;
		public const int PRINT_PAGE_WIDTH = 700;
		public const int PRINT_PAGE_HEIGHT = 900;
		public const int PDF_PAGE_WIDTH = 750;
		public const int PDF_PAGE_HEIGHT = 1060;
		public const int GOOGLE_MAPS = 0;
		public const int OPEN_STREET_MAPS = 1;
		public const int BING_MAPS = 2;
		public const int FLASH_CAPTCHA = 0;
		public const int RE_CAPTCHA = 1;
		public const int AA_TO_LIST = 0;
		public const int AA_TO_ADD = 1;
		public const int AA_TO_VIEW = 2;
		public const int AA_TO_EDIT = 3;
		public const int AA_TO_DETAIL_ADD = 4;
		public const int AA_TO_DETAIL_LIST = 5;
		public const int AE_TO_LIST = 0;
		public const int AE_TO_EDIT = 1;
		public const int AE_TO_VIEW = 2;
		public const int AE_TO_NEXT_EDIT = 3;
		public const int AE_TO_PREV_EDIT = 4;
		public const int AE_TO_DETAIL_LIST = 5;
		public const int BOOTSTRAP_LAYOUT = 3;
		public const int ICON_NONE = 0;
		public const int ICON_FILE = 1;
		public const int ICON_BOOTSTRAP_GLYPH = 2;
		public const string WELCOME_MENU = "welcome_page";
		public const string MENU_VERTICAL = "v";
		public const string MENU_HORIZONTAL = "h";
		public const string MENU_QUICKJUMP = "q";
		public const int SSEARCH_PARAMS_TYPE = 1;
		public const int CRESIZE_PARAMS_TYPE = 2;
		public const int SHFIELDS_PARAMS_TYPE = 3;
		public const int FORDER_PARAMS_TYPE = 4;
		public const string RPM_SEND = "SEND";
		public const string RPM_RESET = "RESET";
		public const int CONTEXT_GLOBAL = 0;
		public const int CONTEXT_PAGE = 1;
		public const int CONTEXT_BUTTON = 2;
		public const int CONTEXT_LOOKUP = 3;
		public const int CONTEXT_ROW = 4;
		public const int BOTH_RECORDS = 0;
		public const int NEXT_RECORD = 1;
		public const int PREV_RECORD = 2;
		public const int F_AGG = 1;
		public const int F_SIMPLE = 2;
		public const int FieldHeaders = 40;
		public const int GlobalSumary = 31;
		public const int GlobalSumaryAvg = 35;
		public const int GlobalSumaryMax = 33;
		public const int GlobalSumaryMin = 32;
		public const int GlobalSumarySum = 34;
		public const int Group1FooterAvg = 6;
		public const int Group1FooterCount = 2;
		public const int Group1FooterMax = 4;
		public const int Group1FooterMin = 3;
		public const int Group1FooterSum = 5;
		public const int Group1Header = 1;
		public const int Group1Summary = 36;
		public const int Group2FooterAvg = 12;
		public const int Group2FooterCount = 8;
		public const int Group2FooterMax = 10;
		public const int Group2FooterMin = 9;
		public const int Group2FooterSum = 11;
		public const int Group2Header = 7;
		public const int Group2Summary = 37;
		public const int Group3FooterAvg = 18;
		public const int Group3FooterCount = 14;
		public const int Group3FooterMax = 16;
		public const int Group3FooterMin = 15;
		public const int Group3FooterSum = 17;
		public const int Group3Header = 13;
		public const int Group3Summary = 38;
		public const int Group4FooterAvg = 24;
		public const int Group4FooterCount = 20;
		public const int Group4FooterMax = 22;
		public const int Group4FooterMin = 21;
		public const int Group4FooterSum = 23;
		public const int Group4Header = 19;
		public const int Group4Summary = 39;
		public const int LE_AND = 1;
		public const int LE_EQ = 2;
		public const int LE_ISNULL = 1;
		public const int LE_OR = 2;
		public const int PageSummary = 26;
		public const int PageSummaryAvg = 30;
		public const int PageSummaryMax = 28;
		public const int PageSummaryMin = 27;
		public const int PageSummarySum = 29;
		public const int TableData = 25;
		public const int E_USER_ERROR = 256;
		public const int E_ERROR = 1;
		public const int SORT_STRING = 2;
		public const int CASE_UPPER = 1;
		public const int CASE_LOWER = 0;
		public const int PREG_SPLIT_DELIM_CAPTURE = 1;
	}
}
