using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_dbo_vwABCReportsVoteCount
	{
		static public void Apply()
		{
			SettingsMap arrAddTabs = SettingsMap.GetArray(), arrEditTabs = SettingsMap.GetArray(), arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), arrRegisterTabs = SettingsMap.GetArray(), arrViewTabs = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), popupPagesLayoutNames = SettingsMap.GetArray(), query = null, queryData_Array = new XVar(), reportGroupFields = SettingsMap.GetArray(), rgroupField = SettingsMap.GetArray(), strOriginalDetailsTable = null, tabFields = SettingsMap.GetArray(), table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"] = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".truncateText"] = true;
			tdataArray["dbo_vwABCReportsVoteCount"][".NumberOfChars"] = 80;
			tdataArray["dbo_vwABCReportsVoteCount"][".ShortName"] = "dbo_vwABCReportsVoteCount";
			tdataArray["dbo_vwABCReportsVoteCount"][".OwnerID"] = "";
			tdataArray["dbo_vwABCReportsVoteCount"][".OriginalTable"] = "dbo.vwABCReportsVoteCount";
			fieldLabelsArray["dbo_vwABCReportsVoteCount"] = SettingsMap.GetArray();
			fieldToolTipsArray["dbo_vwABCReportsVoteCount"] = SettingsMap.GetArray();
			pageTitlesArray["dbo_vwABCReportsVoteCount"] = SettingsMap.GetArray();
			placeHoldersArray["dbo_vwABCReportsVoteCount"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["dbo_vwABCReportsVoteCount"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["record"] = "Record";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["record"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["record"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["batch_number"] = "Batch Number";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["batch_number"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["batch_number"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["species"] = "Species";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["species"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["species"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["date_submitted"] = "Date Submitted";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["date_submitted"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["date_submitted"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["date_observed"] = "Date Observed";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["date_observed"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["date_observed"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["location"] = "Location";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["location"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["location"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["url1"] = "Url1";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["url1"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["url1"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["url2"] = "Url2";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["url2"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["url2"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["url3"] = "Url3";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["url3"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["url3"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["url4"] = "Url4";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["url4"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["url4"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["secretary_comments"] = "Secretary Comments";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["secretary_comments"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["secretary_comments"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["date_approved"] = "Date Approved";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["date_approved"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["date_approved"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["accept"] = "Accept";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["accept"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["accept"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["nonaccept"] = "Nonaccept";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["nonaccept"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["nonaccept"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["status"] = "Status";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["status"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["status"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["originalObserver"] = "Original Observer";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["originalObserver"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["originalObserver"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["submittedby"] = "Submittedby";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["submittedby"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["submittedby"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["additionalObservers"] = "Additional Observers";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["additionalObservers"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["additionalObservers"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["parent_batch_number"] = "Parent Batch Number";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["parent_batch_number"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["parent_batch_number"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["votingCycle"] = "Voting Cycle";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["votingCycle"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["votingCycle"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["groupNumber"] = "Group Number";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["groupNumber"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["groupNumber"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["votecount"] = "Votecount";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["votecount"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["votecount"] = "";
				fieldLabelsArray["dbo_vwABCReportsVoteCount"]["English"]["id"] = "Id";
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"]["id"] = "";
				placeHoldersArray["dbo_vwABCReportsVoteCount"]["English"]["id"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["dbo_vwABCReportsVoteCount"]["English"])))
				{
					tdataArray["dbo_vwABCReportsVoteCount"][".isUseToolTips"] = true;
				}
			}
			if(CommonFunctions.mlang_getcurrentlang() == "")
			{
				fieldLabelsArray["dbo_vwABCReportsVoteCount"][""] = SettingsMap.GetArray();
				fieldToolTipsArray["dbo_vwABCReportsVoteCount"][""] = SettingsMap.GetArray();
				placeHoldersArray["dbo_vwABCReportsVoteCount"][""] = SettingsMap.GetArray();
				pageTitlesArray["dbo_vwABCReportsVoteCount"][""] = SettingsMap.GetArray();
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["dbo_vwABCReportsVoteCount"][""])))
				{
					tdataArray["dbo_vwABCReportsVoteCount"][".isUseToolTips"] = true;
				}
			}
			tdataArray["dbo_vwABCReportsVoteCount"][".NCSearch"] = true;
			tdataArray["dbo_vwABCReportsVoteCount"][".shortTableName"] = "dbo_vwABCReportsVoteCount";
			tdataArray["dbo_vwABCReportsVoteCount"][".nSecOptions"] = 0;
			tdataArray["dbo_vwABCReportsVoteCount"][".recsPerRowPrint"] = 1;
			tdataArray["dbo_vwABCReportsVoteCount"][".mainTableOwnerID"] = "";
			tdataArray["dbo_vwABCReportsVoteCount"][".moveNext"] = 1;
			tdataArray["dbo_vwABCReportsVoteCount"][".entityType"] = 0;
			tdataArray["dbo_vwABCReportsVoteCount"][".strOriginalTableName"] = "dbo.vwABCReportsVoteCount";
			tdataArray["dbo_vwABCReportsVoteCount"][".showAddInPopup"] = false;
			tdataArray["dbo_vwABCReportsVoteCount"][".showEditInPopup"] = false;
			tdataArray["dbo_vwABCReportsVoteCount"][".showViewInPopup"] = false;
			popupPagesLayoutNames = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".popupPagesLayoutNames"] = popupPagesLayoutNames;
			tdataArray["dbo_vwABCReportsVoteCount"][".fieldsForRegister"] = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".listAjax"] = false;
			tdataArray["dbo_vwABCReportsVoteCount"][".audit"] = false;
			tdataArray["dbo_vwABCReportsVoteCount"][".locking"] = false;
			tdataArray["dbo_vwABCReportsVoteCount"][".list"] = true;
			tdataArray["dbo_vwABCReportsVoteCount"][".inlineEdit"] = true;
			tdataArray["dbo_vwABCReportsVoteCount"][".reorderRecordsByHeader"] = true;
			tdataArray["dbo_vwABCReportsVoteCount"][".exportFormatting"] = 2;
			tdataArray["dbo_vwABCReportsVoteCount"][".exportDelimiter"] = ",";
			tdataArray["dbo_vwABCReportsVoteCount"][".exportTo"] = true;
			tdataArray["dbo_vwABCReportsVoteCount"][".printFriendly"] = true;
			tdataArray["dbo_vwABCReportsVoteCount"][".showSimpleSearchOptions"] = false;
			tdataArray["dbo_vwABCReportsVoteCount"][".allowShowHideFields"] = false;
			tdataArray["dbo_vwABCReportsVoteCount"][".allowFieldsReordering"] = false;
			tdataArray["dbo_vwABCReportsVoteCount"][".searchSaving"] = false;
			tdataArray["dbo_vwABCReportsVoteCount"][".showSearchPanel"] = true;
			tdataArray["dbo_vwABCReportsVoteCount"][".flexibleSearch"] = true;
			tdataArray["dbo_vwABCReportsVoteCount"][".isUseAjaxSuggest"] = true;
			tdataArray["dbo_vwABCReportsVoteCount"][".rowHighlite"] = true;


			tdataArray["dbo_vwABCReportsVoteCount"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["dbo_vwABCReportsVoteCount"][".buttonsAdded"] = false;
			tdataArray["dbo_vwABCReportsVoteCount"][".addPageEvents"] = false;
			tdataArray["dbo_vwABCReportsVoteCount"][".isUseTimeForSearch"] = false;
			tdataArray["dbo_vwABCReportsVoteCount"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".allSearchFields"].Add("record");
			tdataArray["dbo_vwABCReportsVoteCount"][".allSearchFields"].Add("batch_number");
			tdataArray["dbo_vwABCReportsVoteCount"][".allSearchFields"].Add("species");
			tdataArray["dbo_vwABCReportsVoteCount"][".allSearchFields"].Add("date_submitted");
			tdataArray["dbo_vwABCReportsVoteCount"][".allSearchFields"].Add("date_observed");
			tdataArray["dbo_vwABCReportsVoteCount"][".allSearchFields"].Add("location");
			tdataArray["dbo_vwABCReportsVoteCount"][".allSearchFields"].Add("secretary_comments");
			tdataArray["dbo_vwABCReportsVoteCount"][".allSearchFields"].Add("date_approved");
			tdataArray["dbo_vwABCReportsVoteCount"][".allSearchFields"].Add("accept");
			tdataArray["dbo_vwABCReportsVoteCount"][".allSearchFields"].Add("nonaccept");
			tdataArray["dbo_vwABCReportsVoteCount"][".allSearchFields"].Add("status");
			tdataArray["dbo_vwABCReportsVoteCount"][".allSearchFields"].Add("originalObserver");
			tdataArray["dbo_vwABCReportsVoteCount"][".allSearchFields"].Add("submittedby");
			tdataArray["dbo_vwABCReportsVoteCount"][".allSearchFields"].Add("additionalObservers");
			tdataArray["dbo_vwABCReportsVoteCount"][".allSearchFields"].Add("parent_batch_number");
			tdataArray["dbo_vwABCReportsVoteCount"][".allSearchFields"].Add("votingCycle");
			tdataArray["dbo_vwABCReportsVoteCount"][".allSearchFields"].Add("groupNumber");
			tdataArray["dbo_vwABCReportsVoteCount"][".allSearchFields"].Add("votecount");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("record");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("batch_number");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("species");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("date_submitted");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("date_observed");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("location");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("url1");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("url2");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("url3");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("url4");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("secretary_comments");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("date_approved");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("accept");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("nonaccept");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("status");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("originalObserver");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("submittedby");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("additionalObservers");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("parent_batch_number");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("votingCycle");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("groupNumber");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("votecount");
			tdataArray["dbo_vwABCReportsVoteCount"][".googleLikeFields"].Add("id");
			tdataArray["dbo_vwABCReportsVoteCount"][".advSearchFields"] = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".advSearchFields"].Add("record");
			tdataArray["dbo_vwABCReportsVoteCount"][".advSearchFields"].Add("batch_number");
			tdataArray["dbo_vwABCReportsVoteCount"][".advSearchFields"].Add("species");
			tdataArray["dbo_vwABCReportsVoteCount"][".advSearchFields"].Add("date_submitted");
			tdataArray["dbo_vwABCReportsVoteCount"][".advSearchFields"].Add("date_observed");
			tdataArray["dbo_vwABCReportsVoteCount"][".advSearchFields"].Add("location");
			tdataArray["dbo_vwABCReportsVoteCount"][".advSearchFields"].Add("secretary_comments");
			tdataArray["dbo_vwABCReportsVoteCount"][".advSearchFields"].Add("date_approved");
			tdataArray["dbo_vwABCReportsVoteCount"][".advSearchFields"].Add("accept");
			tdataArray["dbo_vwABCReportsVoteCount"][".advSearchFields"].Add("nonaccept");
			tdataArray["dbo_vwABCReportsVoteCount"][".advSearchFields"].Add("status");
			tdataArray["dbo_vwABCReportsVoteCount"][".advSearchFields"].Add("originalObserver");
			tdataArray["dbo_vwABCReportsVoteCount"][".advSearchFields"].Add("submittedby");
			tdataArray["dbo_vwABCReportsVoteCount"][".advSearchFields"].Add("additionalObservers");
			tdataArray["dbo_vwABCReportsVoteCount"][".advSearchFields"].Add("parent_batch_number");
			tdataArray["dbo_vwABCReportsVoteCount"][".advSearchFields"].Add("votingCycle");
			tdataArray["dbo_vwABCReportsVoteCount"][".advSearchFields"].Add("groupNumber");
			tdataArray["dbo_vwABCReportsVoteCount"][".advSearchFields"].Add("votecount");
			tdataArray["dbo_vwABCReportsVoteCount"][".tableType"] = "list";
			tdataArray["dbo_vwABCReportsVoteCount"][".printerPageOrientation"] = 0;
			tdataArray["dbo_vwABCReportsVoteCount"][".nPrinterPageScale"] = 100;
			tdataArray["dbo_vwABCReportsVoteCount"][".nPrinterSplitRecords"] = 40;
			tdataArray["dbo_vwABCReportsVoteCount"][".nPrinterPDFSplitRecords"] = 40;
			tdataArray["dbo_vwABCReportsVoteCount"][".geocodingEnabled"] = false;
			tdataArray["dbo_vwABCReportsVoteCount"][".listGridLayout"] = 3;
			tdataArray["dbo_vwABCReportsVoteCount"][".pageSize"] = 20;
			tdataArray["dbo_vwABCReportsVoteCount"][".warnLeavingPages"] = true;
			tstrOrderBy = "ORDER BY votecount DESC";
			if(MVCFunctions.strlen(tstrOrderBy) && MVCFunctions.strtolower(MVCFunctions.substr(tstrOrderBy, new XVar(0), new XVar(8))) != "order by")
			{
				tstrOrderBy = MVCFunctions.Concat("order by ", tstrOrderBy);
			}
			tdataArray["dbo_vwABCReportsVoteCount"][".strOrderBy"] = tstrOrderBy;
			tdataArray["dbo_vwABCReportsVoteCount"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".orderindexes"].Add(new XVar(0, 22, 1, (XVar.Pack(0) ? XVar.Pack("ASC") : XVar.Pack("DESC")), 2, "Votecount"));
			tdataArray["dbo_vwABCReportsVoteCount"][".sqlHead"] = "SELECT [record],  batch_number,  species,  date_submitted,  date_observed,  location,  url1,  url2,  url3,  url4,  secretary_comments,  date_approved,  accept,  nonaccept,  status,  originalObserver,  submittedby,  additionalObservers,  parent_batch_number,  votingCycle,  groupNumber,  votecount,  id";
			tdataArray["dbo_vwABCReportsVoteCount"][".sqlFrom"] = "FROM dbo.vwABCReportsVoteCount";
			tdataArray["dbo_vwABCReportsVoteCount"][".sqlWhereExpr"] = "";
			tdataArray["dbo_vwABCReportsVoteCount"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["dbo_vwABCReportsVoteCount"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["dbo_vwABCReportsVoteCount"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["dbo_vwABCReportsVoteCount"][".highlightSearchResults"] = true;
			tableKeysArray["dbo_vwABCReportsVoteCount"] = SettingsMap.GetArray();
			tableKeysArray["dbo_vwABCReportsVoteCount"].Add("record");
			tableKeysArray["dbo_vwABCReportsVoteCount"].Add("id");
			tdataArray["dbo_vwABCReportsVoteCount"][".Keys"] = tableKeysArray["dbo_vwABCReportsVoteCount"];
			tdataArray["dbo_vwABCReportsVoteCount"][".listFields"] = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".listFields"].Add("batch_number");
			tdataArray["dbo_vwABCReportsVoteCount"][".listFields"].Add("species");
			tdataArray["dbo_vwABCReportsVoteCount"][".listFields"].Add("date_submitted");
			tdataArray["dbo_vwABCReportsVoteCount"][".listFields"].Add("date_observed");
			tdataArray["dbo_vwABCReportsVoteCount"][".listFields"].Add("location");
			tdataArray["dbo_vwABCReportsVoteCount"][".listFields"].Add("secretary_comments");
			tdataArray["dbo_vwABCReportsVoteCount"][".listFields"].Add("url1");
			tdataArray["dbo_vwABCReportsVoteCount"][".listFields"].Add("date_approved");
			tdataArray["dbo_vwABCReportsVoteCount"][".listFields"].Add("accept");
			tdataArray["dbo_vwABCReportsVoteCount"][".listFields"].Add("nonaccept");
			tdataArray["dbo_vwABCReportsVoteCount"][".listFields"].Add("status");
			tdataArray["dbo_vwABCReportsVoteCount"][".listFields"].Add("groupNumber");
			tdataArray["dbo_vwABCReportsVoteCount"][".listFields"].Add("parent_batch_number");
			tdataArray["dbo_vwABCReportsVoteCount"][".listFields"].Add("votingCycle");
			tdataArray["dbo_vwABCReportsVoteCount"][".listFields"].Add("votecount");
			tdataArray["dbo_vwABCReportsVoteCount"][".hideMobileList"] = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".viewFields"] = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".addFields"] = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"] = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("record");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("batch_number");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("species");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("date_submitted");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("date_observed");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("location");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("url1");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("url2");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("url3");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("url4");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("secretary_comments");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("date_approved");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("accept");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("nonaccept");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("status");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("originalObserver");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("submittedby");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("additionalObservers");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("parent_batch_number");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("votingCycle");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("groupNumber");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("votecount");
			tdataArray["dbo_vwABCReportsVoteCount"][".masterListFields"].Add("id");
			tdataArray["dbo_vwABCReportsVoteCount"][".inlineAddFields"] = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".editFields"] = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".inlineEditFields"] = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".inlineEditFields"].Add("date_approved");
			tdataArray["dbo_vwABCReportsVoteCount"][".inlineEditFields"].Add("accept");
			tdataArray["dbo_vwABCReportsVoteCount"][".inlineEditFields"].Add("nonaccept");
			tdataArray["dbo_vwABCReportsVoteCount"][".inlineEditFields"].Add("status");
			tdataArray["dbo_vwABCReportsVoteCount"][".inlineEditFields"].Add("groupNumber");
			tdataArray["dbo_vwABCReportsVoteCount"][".updateSelectedFields"] = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".exportFields"] = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".importFields"] = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"] = SettingsMap.GetArray();
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("record");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("batch_number");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("species");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("date_submitted");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("date_observed");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("location");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("url1");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("url2");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("url3");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("url4");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("secretary_comments");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("date_approved");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("accept");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("nonaccept");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("status");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("originalObserver");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("submittedby");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("additionalObservers");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("parent_batch_number");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("votingCycle");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("groupNumber");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("votecount");
			tdataArray["dbo_vwABCReportsVoteCount"][".printFields"].Add("id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "record";
			fdata["GoodName"] = "record";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","record");
			fdata["FieldType"] = 202;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "record";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "[record]";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			tdataArray["dbo_vwABCReportsVoteCount"]["record"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "batch_number";
			fdata["GoodName"] = "batch_number";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","batch_number");
			fdata["FieldType"] = 202;
			fdata["bListPage"] = true;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "batch_number";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "batch_number";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			tdataArray["dbo_vwABCReportsVoteCount"]["batch_number"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "species";
			fdata["GoodName"] = "species";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","species");
			fdata["FieldType"] = 202;
			fdata["bListPage"] = true;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "species";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "species";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			tdataArray["dbo_vwABCReportsVoteCount"]["species"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "date_submitted";
			fdata["GoodName"] = "date_submitted";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","date_submitted");
			fdata["FieldType"] = 135;
			fdata["bListPage"] = true;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "date_submitted";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "date_submitted";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["ShowTime"] = true;
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			tdataArray["dbo_vwABCReportsVoteCount"]["date_submitted"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "date_observed";
			fdata["GoodName"] = "date_observed";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","date_observed");
			fdata["FieldType"] = 135;
			fdata["bListPage"] = true;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "date_observed";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "date_observed";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["ShowTime"] = true;
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			tdataArray["dbo_vwABCReportsVoteCount"]["date_observed"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "location";
			fdata["GoodName"] = "location";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","location");
			fdata["FieldType"] = 202;
			fdata["bListPage"] = true;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "location";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "location";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			tdataArray["dbo_vwABCReportsVoteCount"]["location"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "url1";
			fdata["GoodName"] = "url1";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","url1");
			fdata["FieldType"] = 202;
			fdata["bListPage"] = true;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "url1";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "url1";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Hyperlink");
			vdata["hlNewWindow"] = true;
			vdata["hlType"] = 1;
			vdata["hlLinkWordNameType"] = "Text";
			vdata["hlLinkWordText"] = "Link";
			vdata["hlTitleField"] = "";
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			tdataArray["dbo_vwABCReportsVoteCount"]["url1"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "url2";
			fdata["GoodName"] = "url2";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","url2");
			fdata["FieldType"] = 202;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "url2";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "url2";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			tdataArray["dbo_vwABCReportsVoteCount"]["url2"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "url3";
			fdata["GoodName"] = "url3";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","url3");
			fdata["FieldType"] = 202;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "url3";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "url3";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			tdataArray["dbo_vwABCReportsVoteCount"]["url3"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "url4";
			fdata["GoodName"] = "url4";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","url4");
			fdata["FieldType"] = 202;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "url4";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "url4";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			tdataArray["dbo_vwABCReportsVoteCount"]["url4"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "secretary_comments";
			fdata["GoodName"] = "secretary_comments";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","secretary_comments");
			fdata["FieldType"] = 202;
			fdata["bListPage"] = true;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "secretary_comments";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "secretary_comments";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			tdataArray["dbo_vwABCReportsVoteCount"]["secretary_comments"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "date_approved";
			fdata["GoodName"] = "date_approved";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","date_approved");
			fdata["FieldType"] = 135;
			fdata["bListPage"] = true;
			fdata["bInlineEdit"] = true;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "date_approved";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "date_approved";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["IsRequired"] = true;
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 11;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			edata["autoUpdatable"] = true;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			tdataArray["dbo_vwABCReportsVoteCount"]["date_approved"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 13;
			fdata["strName"] = "accept";
			fdata["GoodName"] = "accept";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","accept");
			fdata["FieldType"] = 11;
			fdata["bListPage"] = true;
			fdata["bInlineEdit"] = true;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "accept";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "accept";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Checkbox");
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Checkbox");
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			tdataArray["dbo_vwABCReportsVoteCount"]["accept"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 14;
			fdata["strName"] = "nonaccept";
			fdata["GoodName"] = "nonaccept";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","nonaccept");
			fdata["FieldType"] = 11;
			fdata["bListPage"] = true;
			fdata["bInlineEdit"] = true;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "nonaccept";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "nonaccept";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Checkbox");
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Checkbox");
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			tdataArray["dbo_vwABCReportsVoteCount"]["nonaccept"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 15;
			fdata["strName"] = "status";
			fdata["GoodName"] = "status";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","status");
			fdata["FieldType"] = 202;
			fdata["bListPage"] = true;
			fdata["bInlineEdit"] = true;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "status";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "status";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Lookup wizard");
			edata["LookupType"] = 0;
			edata["autoCompleteFieldsOnEdit"] = 0;
			edata["autoCompleteFields"] = SettingsMap.GetArray();
			edata["LCType"] = 0;
			edata["LookupValues"] = SettingsMap.GetArray();
			edata["LookupValues"].Add("Accepted");
			edata["LookupValues"].Add("Non-Accept");
			edata["LookupValues"].Add("Submitted");
			edata["LookupValues"].Add("Not a Review Species");
			edata["LookupValues"].Add("Not Reviewable");
			edata["LookupValues"].Add("Non-Accept - Origin");
			edata["SelectSize"] = 1;
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			tdataArray["dbo_vwABCReportsVoteCount"]["status"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 16;
			fdata["strName"] = "originalObserver";
			fdata["GoodName"] = "originalObserver";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","originalObserver");
			fdata["FieldType"] = 202;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "originalObserver";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "originalObserver";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			tdataArray["dbo_vwABCReportsVoteCount"]["originalObserver"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 17;
			fdata["strName"] = "submittedby";
			fdata["GoodName"] = "submittedby";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","submittedby");
			fdata["FieldType"] = 202;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "submittedby";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "submittedby";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			tdataArray["dbo_vwABCReportsVoteCount"]["submittedby"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 18;
			fdata["strName"] = "additionalObservers";
			fdata["GoodName"] = "additionalObservers";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","additionalObservers");
			fdata["FieldType"] = 202;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "additionalObservers";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "additionalObservers";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			tdataArray["dbo_vwABCReportsVoteCount"]["additionalObservers"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 19;
			fdata["strName"] = "parent_batch_number";
			fdata["GoodName"] = "parent_batch_number";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","parent_batch_number");
			fdata["FieldType"] = 202;
			fdata["bListPage"] = true;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "parent_batch_number";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "parent_batch_number";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			tdataArray["dbo_vwABCReportsVoteCount"]["parent_batch_number"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 20;
			fdata["strName"] = "votingCycle";
			fdata["GoodName"] = "votingCycle";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","votingCycle");
			fdata["FieldType"] = 202;
			fdata["bListPage"] = true;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "votingCycle";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "votingCycle";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			tdataArray["dbo_vwABCReportsVoteCount"]["votingCycle"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 21;
			fdata["strName"] = "groupNumber";
			fdata["GoodName"] = "groupNumber";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","groupNumber");
			fdata["FieldType"] = 202;
			fdata["bListPage"] = true;
			fdata["bInlineEdit"] = true;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "groupNumber";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "groupNumber";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			tdataArray["dbo_vwABCReportsVoteCount"]["groupNumber"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 22;
			fdata["strName"] = "votecount";
			fdata["GoodName"] = "votecount";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","votecount");
			fdata["FieldType"] = 3;
			fdata["bListPage"] = true;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "Votecount";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "votecount";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "number";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			tdataArray["dbo_vwABCReportsVoteCount"]["votecount"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 23;
			fdata["strName"] = "id";
			fdata["GoodName"] = "id";
			fdata["ownerTable"] = "dbo.vwABCReportsVoteCount";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_vwABCReportsVoteCount","id");
			fdata["FieldType"] = 3;
			fdata["bPrinterPage"] = true;
			fdata["strField"] = "id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "id";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["IsRequired"] = true;
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "number";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			tdataArray["dbo_vwABCReportsVoteCount"]["id"] = fdata;
			GlobalVars.tables_data["dbo.vwABCReportsVoteCount"] = tdataArray["dbo_vwABCReportsVoteCount"];
			GlobalVars.field_labels["dbo_vwABCReportsVoteCount"] = fieldLabelsArray["dbo_vwABCReportsVoteCount"];
			GlobalVars.fieldToolTips["dbo_vwABCReportsVoteCount"] = fieldToolTipsArray["dbo_vwABCReportsVoteCount"];
			GlobalVars.placeHolders["dbo_vwABCReportsVoteCount"] = placeHoldersArray["dbo_vwABCReportsVoteCount"];
			GlobalVars.page_titles["dbo_vwABCReportsVoteCount"] = pageTitlesArray["dbo_vwABCReportsVoteCount"];
			GlobalVars.detailsTablesData["dbo.vwABCReportsVoteCount"] = SettingsMap.GetArray();


			dIndex = 0;
			detailsParam = SettingsMap.GetArray();
			detailsParam["dDataSourceTable"] = "dbo._ABCVotes";
			detailsParam["dOriginalTable"] = "dbo._ABCVotes";
			detailsParam["proceedLink"] = true;
			detailsParam["dType"] = Constants.PAGE_LIST;
			detailsParam["dShortTable"] = "dbo__ABCVotes";
			detailsParam["dCaptionTable"] = CommonFunctions.GetTableCaption(new XVar("dbo__ABCVotes"));
			detailsParam["masterKeys"] = SettingsMap.GetArray();
			detailsParam["detailKeys"] = SettingsMap.GetArray();
			detailsParam["dispChildCount"] = "0";
			detailsParam["hideChild"] = false;
			detailsParam["previewOnList"] = "1";
			detailsParam["previewOnAdd"] = 0;
			detailsParam["previewOnEdit"] = 0;
			detailsParam["previewOnView"] = 0;
			GlobalVars.detailsTablesData["dbo.vwABCReportsVoteCount"][dIndex] = detailsParam;
			GlobalVars.detailsTablesData["dbo.vwABCReportsVoteCount"][dIndex]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.detailsTablesData["dbo.vwABCReportsVoteCount"][dIndex]["masterKeys"].Add("record");
			GlobalVars.detailsTablesData["dbo.vwABCReportsVoteCount"][dIndex]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.detailsTablesData["dbo.vwABCReportsVoteCount"][dIndex]["detailKeys"].Add("record");
			GlobalVars.masterTablesData["dbo.vwABCReportsVoteCount"] = SettingsMap.GetArray();

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "[record],  batch_number,  species,  date_submitted,  date_observed,  location,  url1,  url2,  url3,  url4,  secretary_comments,  date_approved,  accept,  nonaccept,  status,  originalObserver,  submittedby,  additionalObservers,  parent_batch_number,  votingCycle,  groupNumber,  votecount,  id";
protoArray["0"]["m_strFrom"] = "FROM dbo.vwABCReportsVoteCount";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "ORDER BY votecount DESC";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "record", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["6"]["m_sql"] = "[record]";
protoArray["6"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "batch_number", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["8"]["m_sql"] = "batch_number";
protoArray["8"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "species", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["10"]["m_sql"] = "species";
protoArray["10"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "date_submitted", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["12"]["m_sql"] = "date_submitted";
protoArray["12"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "date_observed", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["14"]["m_sql"] = "date_observed";
protoArray["14"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "location", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["16"]["m_sql"] = "location";
protoArray["16"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "url1", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["18"]["m_sql"] = "url1";
protoArray["18"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "url2", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["20"]["m_sql"] = "url2";
protoArray["20"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "url3", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["22"]["m_sql"] = "url3";
protoArray["22"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "url4", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["24"]["m_sql"] = "url4";
protoArray["24"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "secretary_comments", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["26"]["m_sql"] = "secretary_comments";
protoArray["26"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["28"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "date_approved", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["28"]["m_sql"] = "date_approved";
protoArray["28"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["28"]["m_expr"] = obj;
protoArray["28"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["28"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["30"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "accept", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["30"]["m_sql"] = "accept";
protoArray["30"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["30"]["m_expr"] = obj;
protoArray["30"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["30"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["32"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "nonaccept", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["32"]["m_sql"] = "nonaccept";
protoArray["32"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["32"]["m_expr"] = obj;
protoArray["32"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["32"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["34"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "status", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["34"]["m_sql"] = "status";
protoArray["34"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["34"]["m_expr"] = obj;
protoArray["34"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["34"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["36"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "originalObserver", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["36"]["m_sql"] = "originalObserver";
protoArray["36"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["36"]["m_expr"] = obj;
protoArray["36"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["36"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["38"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "submittedby", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["38"]["m_sql"] = "submittedby";
protoArray["38"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["38"]["m_expr"] = obj;
protoArray["38"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["38"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["40"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "additionalObservers", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["40"]["m_sql"] = "additionalObservers";
protoArray["40"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["40"]["m_expr"] = obj;
protoArray["40"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["40"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["42"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "parent_batch_number", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["42"]["m_sql"] = "parent_batch_number";
protoArray["42"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["42"]["m_expr"] = obj;
protoArray["42"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["42"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["44"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "votingCycle", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["44"]["m_sql"] = "votingCycle";
protoArray["44"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["44"]["m_expr"] = obj;
protoArray["44"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["44"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["46"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "groupNumber", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["46"]["m_sql"] = "groupNumber";
protoArray["46"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["46"]["m_expr"] = obj;
protoArray["46"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["46"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["48"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "Votecount", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["48"]["m_sql"] = "votecount";
protoArray["48"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["48"]["m_expr"] = obj;
protoArray["48"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["48"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["50"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "id", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["50"]["m_sql"] = "id";
protoArray["50"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["50"]["m_expr"] = obj;
protoArray["50"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["50"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["52"] = SettingsMap.GetArray();
protoArray["52"]["m_link"] = "SQLL_MAIN";
protoArray["53"] = SettingsMap.GetArray();
protoArray["53"]["m_strName"] = "dbo.vwABCReportsVoteCount";
protoArray["53"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["53"]["m_columns"] = SettingsMap.GetArray();
protoArray["53"]["m_columns"].Add("id");
protoArray["53"]["m_columns"].Add("record");
protoArray["53"]["m_columns"].Add("batch_number");
protoArray["53"]["m_columns"].Add("species");
protoArray["53"]["m_columns"].Add("date_submitted");
protoArray["53"]["m_columns"].Add("date_observed");
protoArray["53"]["m_columns"].Add("location");
protoArray["53"]["m_columns"].Add("url1");
protoArray["53"]["m_columns"].Add("url2");
protoArray["53"]["m_columns"].Add("url3");
protoArray["53"]["m_columns"].Add("url4");
protoArray["53"]["m_columns"].Add("secretary_comments");
protoArray["53"]["m_columns"].Add("secretary_private_comments");
protoArray["53"]["m_columns"].Add("date_approved");
protoArray["53"]["m_columns"].Add("accept");
protoArray["53"]["m_columns"].Add("nonaccept");
protoArray["53"]["m_columns"].Add("status");
protoArray["53"]["m_columns"].Add("originalObserver");
protoArray["53"]["m_columns"].Add("submittedby");
protoArray["53"]["m_columns"].Add("additionalObservers");
protoArray["53"]["m_columns"].Add("numberObserved");
protoArray["53"]["m_columns"].Add("countyCode");
protoArray["53"]["m_columns"].Add("beginDate");
protoArray["53"]["m_columns"].Add("endDate");
protoArray["53"]["m_columns"].Add("age");
protoArray["53"]["m_columns"].Add("sex");
protoArray["53"]["m_columns"].Add("plumage");
protoArray["53"]["m_columns"].Add("subspecies");
protoArray["53"]["m_columns"].Add("photo");
protoArray["53"]["m_columns"].Add("video");
protoArray["53"]["m_columns"].Add("audio");
protoArray["53"]["m_columns"].Add("comments");
protoArray["53"]["m_columns"].Add("NABReference");
protoArray["53"]["m_columns"].Add("hide");
protoArray["53"]["m_columns"].Add("parent_batch_number");
protoArray["53"]["m_columns"].Add("published");
protoArray["53"]["m_columns"].Add("publication");
protoArray["53"]["m_columns"].Add("votingCycle");
protoArray["53"]["m_columns"].Add("groupNumber");
protoArray["53"]["m_columns"].Add("Votecount");
obj = new SQLTable(protoArray["53"]);

protoArray["52"]["m_table"] = obj;
protoArray["52"]["m_sql"] = "dbo.vwABCReportsVoteCount";
protoArray["52"]["m_alias"] = "";
protoArray["52"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
protoArray["54"] = SettingsMap.GetArray();
protoArray["54"]["m_sql"] = "";
protoArray["54"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["54"]["m_column"] = obj;
protoArray["54"]["m_contained"] = SettingsMap.GetArray();
protoArray["54"]["m_strCase"] = "";
protoArray["54"]["m_havingmode"] = false;
protoArray["54"]["m_inBrackets"] = false;
protoArray["54"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["54"]);

protoArray["52"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["52"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["56"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "Votecount", "m_strTable", "dbo.vwABCReportsVoteCount", "m_srcTableName", "dbo.vwABCReportsVoteCount"));

protoArray["56"]["m_column"] = obj;
protoArray["56"]["m_bAsc"] = 0;
protoArray["56"]["m_nColumn"] = 0;
obj = new SQLOrderByItem(protoArray["56"]);

protoArray["0"]["m_orderby"].Add(obj);
protoArray["0"]["m_srcTableName"] = "dbo.vwABCReportsVoteCount";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["dbo_vwABCReportsVoteCount"] = obj;

				
		
			tdataArray["dbo_vwABCReportsVoteCount"][".sqlquery"] = queryData_Array["dbo_vwABCReportsVoteCount"];
			GlobalVars.tableEvents["dbo.vwABCReportsVoteCount"] = new eventsBase();
			tdataArray["dbo_vwABCReportsVoteCount"][".hasEvents"] = false;
			GlobalVars.tables_data["dbo_vwABCReportsVoteCount"] = tdataArray["dbo_vwABCReportsVoteCount"];
		}
	}

}
