using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_dbo__ABCVotes
	{
		static public void Apply()
		{
			SettingsMap arrAddTabs = SettingsMap.GetArray(), arrEditTabs = SettingsMap.GetArray(), arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), arrRegisterTabs = SettingsMap.GetArray(), arrViewTabs = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), popupPagesLayoutNames = SettingsMap.GetArray(), query = null, queryData_Array = new XVar(), reportGroupFields = SettingsMap.GetArray(), rgroupField = SettingsMap.GetArray(), strOriginalDetailsTable = null, tabFields = SettingsMap.GetArray(), table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"] = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".truncateText"] = true;
			tdataArray["dbo__ABCVotes"][".NumberOfChars"] = 100;
			tdataArray["dbo__ABCVotes"][".ShortName"] = "dbo__ABCVotes";
			tdataArray["dbo__ABCVotes"][".OwnerID"] = "committee_member";
			tdataArray["dbo__ABCVotes"][".OriginalTable"] = "dbo._ABCVotes";
			fieldLabelsArray["dbo__ABCVotes"] = SettingsMap.GetArray();
			fieldToolTipsArray["dbo__ABCVotes"] = SettingsMap.GetArray();
			pageTitlesArray["dbo__ABCVotes"] = SettingsMap.GetArray();
			placeHoldersArray["dbo__ABCVotes"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["dbo__ABCVotes"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["dbo__ABCVotes"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["dbo__ABCVotes"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["dbo__ABCVotes"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["dbo__ABCVotes"]["English"]["record"] = "Record";
				fieldToolTipsArray["dbo__ABCVotes"]["English"]["record"] = "";
				placeHoldersArray["dbo__ABCVotes"]["English"]["record"] = "";
				fieldLabelsArray["dbo__ABCVotes"]["English"]["committee_member"] = "Committee Member";
				fieldToolTipsArray["dbo__ABCVotes"]["English"]["committee_member"] = "";
				placeHoldersArray["dbo__ABCVotes"]["English"]["committee_member"] = "";
				fieldLabelsArray["dbo__ABCVotes"]["English"]["date_voted"] = "Date Voted";
				fieldToolTipsArray["dbo__ABCVotes"]["English"]["date_voted"] = "";
				placeHoldersArray["dbo__ABCVotes"]["English"]["date_voted"] = "";
				fieldLabelsArray["dbo__ABCVotes"]["English"]["vote"] = "Vote";
				fieldToolTipsArray["dbo__ABCVotes"]["English"]["vote"] = "";
				placeHoldersArray["dbo__ABCVotes"]["English"]["vote"] = "";
				fieldLabelsArray["dbo__ABCVotes"]["English"]["comment"] = "Comments";
				fieldToolTipsArray["dbo__ABCVotes"]["English"]["comment"] = "";
				placeHoldersArray["dbo__ABCVotes"]["English"]["comment"] = "";
				fieldLabelsArray["dbo__ABCVotes"]["English"]["id"] = "Id";
				fieldToolTipsArray["dbo__ABCVotes"]["English"]["id"] = "";
				placeHoldersArray["dbo__ABCVotes"]["English"]["id"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["dbo__ABCVotes"]["English"])))
				{
					tdataArray["dbo__ABCVotes"][".isUseToolTips"] = true;
				}
			}
			if(CommonFunctions.mlang_getcurrentlang() == "")
			{
				fieldLabelsArray["dbo__ABCVotes"][""] = SettingsMap.GetArray();
				fieldToolTipsArray["dbo__ABCVotes"][""] = SettingsMap.GetArray();
				placeHoldersArray["dbo__ABCVotes"][""] = SettingsMap.GetArray();
				pageTitlesArray["dbo__ABCVotes"][""] = SettingsMap.GetArray();
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["dbo__ABCVotes"][""])))
				{
					tdataArray["dbo__ABCVotes"][".isUseToolTips"] = true;
				}
			}
			tdataArray["dbo__ABCVotes"][".NCSearch"] = true;
			tdataArray["dbo__ABCVotes"][".shortTableName"] = "dbo__ABCVotes";
			tdataArray["dbo__ABCVotes"][".nSecOptions"] = 2;
			tdataArray["dbo__ABCVotes"][".recsPerRowPrint"] = 1;
			tdataArray["dbo__ABCVotes"][".mainTableOwnerID"] = "committee_member";
			tdataArray["dbo__ABCVotes"][".moveNext"] = 1;
			tdataArray["dbo__ABCVotes"][".entityType"] = 0;
			tdataArray["dbo__ABCVotes"][".strOriginalTableName"] = "dbo._ABCVotes";
			tdataArray["dbo__ABCVotes"][".showAddInPopup"] = false;
			tdataArray["dbo__ABCVotes"][".showEditInPopup"] = false;
			tdataArray["dbo__ABCVotes"][".showViewInPopup"] = false;
			popupPagesLayoutNames = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".popupPagesLayoutNames"] = popupPagesLayoutNames;
			tdataArray["dbo__ABCVotes"][".fieldsForRegister"] = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".listAjax"] = false;
			tdataArray["dbo__ABCVotes"][".audit"] = false;
			tdataArray["dbo__ABCVotes"][".locking"] = false;
			tdataArray["dbo__ABCVotes"][".edit"] = true;
			tdataArray["dbo__ABCVotes"][".afterEditAction"] = 1;
			tdataArray["dbo__ABCVotes"][".closePopupAfterEdit"] = 1;
			tdataArray["dbo__ABCVotes"][".afterEditActionDetTable"] = "dbo._ABCSecurity";
			tdataArray["dbo__ABCVotes"][".add"] = true;
			tdataArray["dbo__ABCVotes"][".afterAddAction"] = 0;
			tdataArray["dbo__ABCVotes"][".closePopupAfterAdd"] = 1;
			tdataArray["dbo__ABCVotes"][".afterAddActionDetTable"] = "dbo._ABCSecurity";
			tdataArray["dbo__ABCVotes"][".list"] = true;
			tdataArray["dbo__ABCVotes"][".inlineEdit"] = true;
			tdataArray["dbo__ABCVotes"][".reorderRecordsByHeader"] = true;
			tdataArray["dbo__ABCVotes"][".exportFormatting"] = 2;
			tdataArray["dbo__ABCVotes"][".exportDelimiter"] = ",";
			tdataArray["dbo__ABCVotes"][".inlineAdd"] = true;
			tdataArray["dbo__ABCVotes"][".import"] = true;
			tdataArray["dbo__ABCVotes"][".exportTo"] = true;
			tdataArray["dbo__ABCVotes"][".printFriendly"] = true;
			tdataArray["dbo__ABCVotes"][".delete"] = true;
			tdataArray["dbo__ABCVotes"][".showSimpleSearchOptions"] = false;
			tdataArray["dbo__ABCVotes"][".allowShowHideFields"] = false;
			tdataArray["dbo__ABCVotes"][".allowFieldsReordering"] = false;
			tdataArray["dbo__ABCVotes"][".searchSaving"] = false;
			tdataArray["dbo__ABCVotes"][".showSearchPanel"] = true;
			tdataArray["dbo__ABCVotes"][".flexibleSearch"] = true;
			tdataArray["dbo__ABCVotes"][".isUseAjaxSuggest"] = true;
			tdataArray["dbo__ABCVotes"][".rowHighlite"] = true;


			tdataArray["dbo__ABCVotes"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["dbo__ABCVotes"][".buttonsAdded"] = false;
			tdataArray["dbo__ABCVotes"][".addPageEvents"] = false;
			tdataArray["dbo__ABCVotes"][".isUseTimeForSearch"] = false;
			tdataArray["dbo__ABCVotes"][".badgeColor"] = "BC8F8F";
			tdataArray["dbo__ABCVotes"][".detailsLinksOnList"] = "2";
			tdataArray["dbo__ABCVotes"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".allSearchFields"].Add("committee_member");
			tdataArray["dbo__ABCVotes"][".allSearchFields"].Add("date_voted");
			tdataArray["dbo__ABCVotes"][".allSearchFields"].Add("vote");
			tdataArray["dbo__ABCVotes"][".allSearchFields"].Add("comment");
			tdataArray["dbo__ABCVotes"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".googleLikeFields"].Add("record");
			tdataArray["dbo__ABCVotes"][".googleLikeFields"].Add("committee_member");
			tdataArray["dbo__ABCVotes"][".googleLikeFields"].Add("date_voted");
			tdataArray["dbo__ABCVotes"][".googleLikeFields"].Add("vote");
			tdataArray["dbo__ABCVotes"][".googleLikeFields"].Add("comment");
			tdataArray["dbo__ABCVotes"][".googleLikeFields"].Add("id");
			tdataArray["dbo__ABCVotes"][".advSearchFields"] = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".advSearchFields"].Add("committee_member");
			tdataArray["dbo__ABCVotes"][".advSearchFields"].Add("date_voted");
			tdataArray["dbo__ABCVotes"][".advSearchFields"].Add("vote");
			tdataArray["dbo__ABCVotes"][".advSearchFields"].Add("comment");
			tdataArray["dbo__ABCVotes"][".tableType"] = "list";
			tdataArray["dbo__ABCVotes"][".printerPageOrientation"] = 0;
			tdataArray["dbo__ABCVotes"][".nPrinterPageScale"] = 100;
			tdataArray["dbo__ABCVotes"][".nPrinterSplitRecords"] = 40;
			tdataArray["dbo__ABCVotes"][".nPrinterPDFSplitRecords"] = 40;
			tdataArray["dbo__ABCVotes"][".geocodingEnabled"] = false;
			tdataArray["dbo__ABCVotes"][".listGridLayout"] = 3;
			tdataArray["dbo__ABCVotes"][".isViewPagePDF"] = true;
			tdataArray["dbo__ABCVotes"][".nViewPagePDFScale"] = 100;
			tdataArray["dbo__ABCVotes"][".isPrinterPagePDF"] = true;
			tdataArray["dbo__ABCVotes"][".nPrinterPagePDFScale"] = 100;
			tdataArray["dbo__ABCVotes"][".pageSize"] = 20;
			tdataArray["dbo__ABCVotes"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			if(MVCFunctions.strlen(tstrOrderBy) && MVCFunctions.strtolower(MVCFunctions.substr(tstrOrderBy, new XVar(0), new XVar(8))) != "order by")
			{
				tstrOrderBy = MVCFunctions.Concat("order by ", tstrOrderBy);
			}
			tdataArray["dbo__ABCVotes"][".strOrderBy"] = tstrOrderBy;
			tdataArray["dbo__ABCVotes"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".sqlHead"] = "SELECT [record],  committee_member,  date_voted,  vote,  [comment],  id";
			tdataArray["dbo__ABCVotes"][".sqlFrom"] = "FROM dbo.[_ABCVotes]";
			tdataArray["dbo__ABCVotes"][".sqlWhereExpr"] = "";
			tdataArray["dbo__ABCVotes"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["dbo__ABCVotes"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["dbo__ABCVotes"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["dbo__ABCVotes"][".highlightSearchResults"] = true;
			tableKeysArray["dbo__ABCVotes"] = SettingsMap.GetArray();
			tableKeysArray["dbo__ABCVotes"].Add("id");
			tableKeysArray["dbo__ABCVotes"].Add("record");
			tdataArray["dbo__ABCVotes"][".Keys"] = tableKeysArray["dbo__ABCVotes"];
			tdataArray["dbo__ABCVotes"][".listFields"] = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".listFields"].Add("committee_member");
			tdataArray["dbo__ABCVotes"][".listFields"].Add("date_voted");
			tdataArray["dbo__ABCVotes"][".listFields"].Add("vote");
			tdataArray["dbo__ABCVotes"][".listFields"].Add("comment");
			tdataArray["dbo__ABCVotes"][".hideMobileList"] = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".viewFields"] = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".addFields"] = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".addFields"].Add("record");
			tdataArray["dbo__ABCVotes"][".addFields"].Add("committee_member");
			tdataArray["dbo__ABCVotes"][".addFields"].Add("date_voted");
			tdataArray["dbo__ABCVotes"][".addFields"].Add("vote");
			tdataArray["dbo__ABCVotes"][".addFields"].Add("comment");
			tdataArray["dbo__ABCVotes"][".masterListFields"] = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".masterListFields"].Add("record");
			tdataArray["dbo__ABCVotes"][".masterListFields"].Add("committee_member");
			tdataArray["dbo__ABCVotes"][".masterListFields"].Add("date_voted");
			tdataArray["dbo__ABCVotes"][".masterListFields"].Add("vote");
			tdataArray["dbo__ABCVotes"][".masterListFields"].Add("comment");
			tdataArray["dbo__ABCVotes"][".masterListFields"].Add("id");
			tdataArray["dbo__ABCVotes"][".inlineAddFields"] = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".inlineAddFields"].Add("committee_member");
			tdataArray["dbo__ABCVotes"][".inlineAddFields"].Add("date_voted");
			tdataArray["dbo__ABCVotes"][".inlineAddFields"].Add("vote");
			tdataArray["dbo__ABCVotes"][".inlineAddFields"].Add("comment");
			tdataArray["dbo__ABCVotes"][".editFields"] = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".editFields"].Add("record");
			tdataArray["dbo__ABCVotes"][".editFields"].Add("committee_member");
			tdataArray["dbo__ABCVotes"][".editFields"].Add("date_voted");
			tdataArray["dbo__ABCVotes"][".editFields"].Add("vote");
			tdataArray["dbo__ABCVotes"][".editFields"].Add("comment");
			tdataArray["dbo__ABCVotes"][".inlineEditFields"] = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".inlineEditFields"].Add("committee_member");
			tdataArray["dbo__ABCVotes"][".inlineEditFields"].Add("date_voted");
			tdataArray["dbo__ABCVotes"][".inlineEditFields"].Add("vote");
			tdataArray["dbo__ABCVotes"][".inlineEditFields"].Add("comment");
			tdataArray["dbo__ABCVotes"][".updateSelectedFields"] = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".updateSelectedFields"].Add("record");
			tdataArray["dbo__ABCVotes"][".updateSelectedFields"].Add("committee_member");
			tdataArray["dbo__ABCVotes"][".updateSelectedFields"].Add("date_voted");
			tdataArray["dbo__ABCVotes"][".updateSelectedFields"].Add("vote");
			tdataArray["dbo__ABCVotes"][".updateSelectedFields"].Add("comment");
			tdataArray["dbo__ABCVotes"][".exportFields"] = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".exportFields"].Add("committee_member");
			tdataArray["dbo__ABCVotes"][".exportFields"].Add("date_voted");
			tdataArray["dbo__ABCVotes"][".exportFields"].Add("vote");
			tdataArray["dbo__ABCVotes"][".exportFields"].Add("comment");
			tdataArray["dbo__ABCVotes"][".importFields"] = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".importFields"].Add("committee_member");
			tdataArray["dbo__ABCVotes"][".importFields"].Add("date_voted");
			tdataArray["dbo__ABCVotes"][".importFields"].Add("vote");
			tdataArray["dbo__ABCVotes"][".importFields"].Add("comment");
			tdataArray["dbo__ABCVotes"][".printFields"] = SettingsMap.GetArray();
			tdataArray["dbo__ABCVotes"][".printFields"].Add("committee_member");
			tdataArray["dbo__ABCVotes"][".printFields"].Add("date_voted");
			tdataArray["dbo__ABCVotes"][".printFields"].Add("vote");
			tdataArray["dbo__ABCVotes"][".printFields"].Add("comment");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "record";
			fdata["GoodName"] = "record";
			fdata["ownerTable"] = "dbo._ABCVotes";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo__ABCVotes","record");
			fdata["FieldType"] = 202;
			fdata["bAddPage"] = true;
			fdata["bEditPage"] = true;
			fdata["bUpdateSelected"] = true;
			fdata["strField"] = "record";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "[record]";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Readonly");
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			tdataArray["dbo__ABCVotes"]["record"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "committee_member";
			fdata["GoodName"] = "committee_member";
			fdata["ownerTable"] = "dbo._ABCVotes";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo__ABCVotes","committee_member");
			fdata["FieldType"] = 202;
			fdata["bListPage"] = true;
			fdata["bAddPage"] = true;
			fdata["bInlineAdd"] = true;
			fdata["bEditPage"] = true;
			fdata["bInlineEdit"] = true;
			fdata["bUpdateSelected"] = true;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["bExportPage"] = true;
			fdata["strField"] = "committee_member";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "committee_member";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["IsRequired"] = true;
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			tdataArray["dbo__ABCVotes"]["committee_member"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "date_voted";
			fdata["GoodName"] = "date_voted";
			fdata["ownerTable"] = "dbo._ABCVotes";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo__ABCVotes","date_voted");
			fdata["FieldType"] = 135;
			fdata["bListPage"] = true;
			fdata["bAddPage"] = true;
			fdata["bInlineAdd"] = true;
			fdata["bEditPage"] = true;
			fdata["bInlineEdit"] = true;
			fdata["bUpdateSelected"] = true;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["bExportPage"] = true;
			fdata["strField"] = "date_voted";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "date_voted";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["IsRequired"] = true;
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			tdataArray["dbo__ABCVotes"]["date_voted"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "vote";
			fdata["GoodName"] = "vote";
			fdata["ownerTable"] = "dbo._ABCVotes";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo__ABCVotes","vote");
			fdata["FieldType"] = 202;
			fdata["bListPage"] = true;
			fdata["bAddPage"] = true;
			fdata["bInlineAdd"] = true;
			fdata["bEditPage"] = true;
			fdata["bInlineEdit"] = true;
			fdata["bUpdateSelected"] = true;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["bExportPage"] = true;
			fdata["strField"] = "vote";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "vote";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Lookup wizard");
			edata["LookupType"] = 0;
			edata["autoCompleteFieldsOnEdit"] = 0;
			edata["autoCompleteFields"] = SettingsMap.GetArray();
			edata["LCType"] = 0;
			edata["LookupValues"] = SettingsMap.GetArray();
			edata["LookupValues"].Add("Accept");
			edata["LookupValues"].Add("Non-Accept");
			edata["LookupValues"].Add("Abstain");
			edata["LookupValues"].Add("Exotic");
			edata["SelectSize"] = 1;
			edata["IsRequired"] = true;
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			tdataArray["dbo__ABCVotes"]["vote"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "comment";
			fdata["GoodName"] = "comment";
			fdata["ownerTable"] = "dbo._ABCVotes";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo__ABCVotes","comment");
			fdata["FieldType"] = 202;
			fdata["bListPage"] = true;
			fdata["bAddPage"] = true;
			fdata["bInlineAdd"] = true;
			fdata["bEditPage"] = true;
			fdata["bInlineEdit"] = true;
			fdata["bUpdateSelected"] = true;
			fdata["bAdvancedSearch"] = true;
			fdata["bPrinterPage"] = true;
			fdata["bExportPage"] = true;
			fdata["strField"] = "comment";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "[comment]";
			fdata["FieldPermissions"] = true;
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["nRows"] = 150;
			edata["nCols"] = 500;
			edata["controlWidth"] = 400;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			tdataArray["dbo__ABCVotes"]["comment"] = fdata;
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "id";
			fdata["GoodName"] = "id";
			fdata["ownerTable"] = "dbo._ABCVotes";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo__ABCVotes","id");
			fdata["FieldType"] = 3;
			fdata["strField"] = "id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Readonly");
			edata["IsRequired"] = true;
			edata["acceptFileTypes"] = ".+$";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			tdataArray["dbo__ABCVotes"]["id"] = fdata;
			GlobalVars.tables_data["dbo._ABCVotes"] = tdataArray["dbo__ABCVotes"];
			GlobalVars.field_labels["dbo__ABCVotes"] = fieldLabelsArray["dbo__ABCVotes"];
			GlobalVars.fieldToolTips["dbo__ABCVotes"] = fieldToolTipsArray["dbo__ABCVotes"];
			GlobalVars.placeHolders["dbo__ABCVotes"] = placeHoldersArray["dbo__ABCVotes"];
			GlobalVars.page_titles["dbo__ABCVotes"] = pageTitlesArray["dbo__ABCVotes"];
			GlobalVars.detailsTablesData["dbo._ABCVotes"] = SettingsMap.GetArray();


			dIndex = 0;
			detailsParam = SettingsMap.GetArray();
			detailsParam["dDataSourceTable"] = "dbo._ABCSecurity";
			detailsParam["dOriginalTable"] = "dbo._ABCSecurity";
			detailsParam["proceedLink"] = true;
			detailsParam["dType"] = Constants.PAGE_LIST;
			detailsParam["dShortTable"] = "dbo__ABCSecurity";
			detailsParam["dCaptionTable"] = CommonFunctions.GetTableCaption(new XVar("dbo__ABCSecurity"));
			detailsParam["masterKeys"] = SettingsMap.GetArray();
			detailsParam["detailKeys"] = SettingsMap.GetArray();
			detailsParam["dispChildCount"] = 0;
			detailsParam["hideChild"] = false;
			detailsParam["previewOnAdd"] = 0;
			detailsParam["previewOnEdit"] = 0;
			detailsParam["previewOnView"] = 0;
			GlobalVars.detailsTablesData["dbo._ABCVotes"][dIndex] = detailsParam;
			GlobalVars.detailsTablesData["dbo._ABCVotes"][dIndex]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.detailsTablesData["dbo._ABCVotes"][dIndex]["masterKeys"].Add("committee_member");
			GlobalVars.detailsTablesData["dbo._ABCVotes"][dIndex]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.detailsTablesData["dbo._ABCVotes"][dIndex]["detailKeys"].Add("username");
			GlobalVars.masterTablesData["dbo._ABCVotes"] = SettingsMap.GetArray();


			strOriginalDetailsTable = "dbo._ABCReports";
			masterParams = SettingsMap.GetArray();
			masterParams["mDataSourceTable"] = "dbo._ABCReports";
			masterParams["mOriginalTable"] = strOriginalDetailsTable;
			masterParams["mShortTable"] = "dbo__ABCReports";
			masterParams["masterKeys"] = SettingsMap.GetArray();
			masterParams["detailKeys"] = SettingsMap.GetArray();
			masterParams["dispChildCount"] = "1";
			masterParams["hideChild"] = "0";
			masterParams["dispMasterInfo"] = SettingsMap.GetArray();
			masterParams["dispMasterInfo"][Constants.PAGE_LIST] = true;
			masterParams["dispMasterInfo"][Constants.PAGE_PRINT] = true;
			masterParams["previewOnList"] = 1;
			masterParams["previewOnAdd"] = 0;
			masterParams["previewOnEdit"] = 0;
			masterParams["previewOnView"] = 1;
			masterParams["proceedLink"] = 1;
			masterParams["type"] = Constants.PAGE_LIST;
			GlobalVars.masterTablesData["dbo._ABCVotes"][0] = masterParams;
			GlobalVars.masterTablesData["dbo._ABCVotes"][0]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo._ABCVotes"][0]["masterKeys"].Add("record");
			GlobalVars.masterTablesData["dbo._ABCVotes"][0]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo._ABCVotes"][0]["detailKeys"].Add("record");


			strOriginalDetailsTable = "dbo._ABCReports";
			masterParams = SettingsMap.GetArray();
			masterParams["mDataSourceTable"] = "ABC_Voting_Submitted";
			masterParams["mOriginalTable"] = strOriginalDetailsTable;
			masterParams["mShortTable"] = "ABC_Voting_Submitted1";
			masterParams["masterKeys"] = SettingsMap.GetArray();
			masterParams["detailKeys"] = SettingsMap.GetArray();
			masterParams["dispChildCount"] = "1";
			masterParams["hideChild"] = "0";
			masterParams["dispMasterInfo"] = SettingsMap.GetArray();
			masterParams["previewOnList"] = 1;
			masterParams["previewOnAdd"] = 0;
			masterParams["previewOnEdit"] = 0;
			masterParams["previewOnView"] = 0;
			masterParams["proceedLink"] = 1;
			masterParams["type"] = Constants.PAGE_LIST;
			GlobalVars.masterTablesData["dbo._ABCVotes"][1] = masterParams;
			GlobalVars.masterTablesData["dbo._ABCVotes"][1]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo._ABCVotes"][1]["masterKeys"].Add("record");
			GlobalVars.masterTablesData["dbo._ABCVotes"][1]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo._ABCVotes"][1]["detailKeys"].Add("record");


			strOriginalDetailsTable = "dbo._ABCReports";
			masterParams = SettingsMap.GetArray();
			masterParams["mDataSourceTable"] = "ABC_Voting_Recirculated";
			masterParams["mOriginalTable"] = strOriginalDetailsTable;
			masterParams["mShortTable"] = "ABC_Voting_Recirculated1";
			masterParams["masterKeys"] = SettingsMap.GetArray();
			masterParams["detailKeys"] = SettingsMap.GetArray();
			masterParams["dispChildCount"] = "1";
			masterParams["hideChild"] = "0";
			masterParams["dispMasterInfo"] = SettingsMap.GetArray();
			masterParams["dispMasterInfo"][Constants.PAGE_LIST] = true;
			masterParams["dispMasterInfo"][Constants.PAGE_PRINT] = true;
			masterParams["previewOnList"] = 1;
			masterParams["previewOnAdd"] = 0;
			masterParams["previewOnEdit"] = 0;
			masterParams["previewOnView"] = 1;
			masterParams["proceedLink"] = 1;
			masterParams["type"] = Constants.PAGE_LIST;
			GlobalVars.masterTablesData["dbo._ABCVotes"][2] = masterParams;
			GlobalVars.masterTablesData["dbo._ABCVotes"][2]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo._ABCVotes"][2]["masterKeys"].Add("record");
			GlobalVars.masterTablesData["dbo._ABCVotes"][2]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo._ABCVotes"][2]["detailKeys"].Add("record");


			strOriginalDetailsTable = "dbo._ABCReports";
			masterParams = SettingsMap.GetArray();
			masterParams["mDataSourceTable"] = "ABC_Voting_My_Voting";
			masterParams["mOriginalTable"] = strOriginalDetailsTable;
			masterParams["mShortTable"] = "ABC_Voting_My_Voting";
			masterParams["masterKeys"] = SettingsMap.GetArray();
			masterParams["detailKeys"] = SettingsMap.GetArray();
			masterParams["dispChildCount"] = "1";
			masterParams["hideChild"] = "0";
			masterParams["dispMasterInfo"] = SettingsMap.GetArray();
			masterParams["dispMasterInfo"][Constants.PAGE_LIST] = true;
			masterParams["dispMasterInfo"][Constants.PAGE_PRINT] = true;
			masterParams["previewOnList"] = 1;
			masterParams["previewOnAdd"] = 0;
			masterParams["previewOnEdit"] = 0;
			masterParams["previewOnView"] = 1;
			masterParams["proceedLink"] = 1;
			masterParams["type"] = Constants.PAGE_LIST;
			GlobalVars.masterTablesData["dbo._ABCVotes"][3] = masterParams;
			GlobalVars.masterTablesData["dbo._ABCVotes"][3]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo._ABCVotes"][3]["masterKeys"].Add("record");
			GlobalVars.masterTablesData["dbo._ABCVotes"][3]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo._ABCVotes"][3]["detailKeys"].Add("record");


			strOriginalDetailsTable = "dbo.vwABCReportsVoteCount";
			masterParams = SettingsMap.GetArray();
			masterParams["mDataSourceTable"] = "dbo.vwABCReportsVoteCount";
			masterParams["mOriginalTable"] = strOriginalDetailsTable;
			masterParams["mShortTable"] = "dbo_vwABCReportsVoteCount";
			masterParams["masterKeys"] = SettingsMap.GetArray();
			masterParams["detailKeys"] = SettingsMap.GetArray();
			masterParams["dispChildCount"] = "0";
			masterParams["hideChild"] = "0";
			masterParams["dispMasterInfo"] = SettingsMap.GetArray();
			masterParams["dispMasterInfo"][Constants.PAGE_LIST] = true;
			masterParams["dispMasterInfo"][Constants.PAGE_PRINT] = true;
			masterParams["previewOnList"] = 1;
			masterParams["previewOnAdd"] = 0;
			masterParams["previewOnEdit"] = 0;
			masterParams["previewOnView"] = 0;
			masterParams["proceedLink"] = 1;
			masterParams["type"] = Constants.PAGE_LIST;
			GlobalVars.masterTablesData["dbo._ABCVotes"][4] = masterParams;
			GlobalVars.masterTablesData["dbo._ABCVotes"][4]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo._ABCVotes"][4]["masterKeys"].Add("record");
			GlobalVars.masterTablesData["dbo._ABCVotes"][4]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo._ABCVotes"][4]["detailKeys"].Add("record");

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "[record],  committee_member,  date_voted,  vote,  [comment],  id";
protoArray["0"]["m_strFrom"] = "FROM dbo.[_ABCVotes]";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "record", "m_strTable", "dbo._ABCVotes", "m_srcTableName", "dbo._ABCVotes"));

protoArray["6"]["m_sql"] = "[record]";
protoArray["6"]["m_srcTableName"] = "dbo._ABCVotes";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "committee_member", "m_strTable", "dbo._ABCVotes", "m_srcTableName", "dbo._ABCVotes"));

protoArray["8"]["m_sql"] = "committee_member";
protoArray["8"]["m_srcTableName"] = "dbo._ABCVotes";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "date_voted", "m_strTable", "dbo._ABCVotes", "m_srcTableName", "dbo._ABCVotes"));

protoArray["10"]["m_sql"] = "date_voted";
protoArray["10"]["m_srcTableName"] = "dbo._ABCVotes";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "vote", "m_strTable", "dbo._ABCVotes", "m_srcTableName", "dbo._ABCVotes"));

protoArray["12"]["m_sql"] = "vote";
protoArray["12"]["m_srcTableName"] = "dbo._ABCVotes";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "comment", "m_strTable", "dbo._ABCVotes", "m_srcTableName", "dbo._ABCVotes"));

protoArray["14"]["m_sql"] = "[comment]";
protoArray["14"]["m_srcTableName"] = "dbo._ABCVotes";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "id", "m_strTable", "dbo._ABCVotes", "m_srcTableName", "dbo._ABCVotes"));

protoArray["16"]["m_sql"] = "id";
protoArray["16"]["m_srcTableName"] = "dbo._ABCVotes";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["18"] = SettingsMap.GetArray();
protoArray["18"]["m_link"] = "SQLL_MAIN";
protoArray["19"] = SettingsMap.GetArray();
protoArray["19"]["m_strName"] = "dbo._ABCVotes";
protoArray["19"]["m_srcTableName"] = "dbo._ABCVotes";
protoArray["19"]["m_columns"] = SettingsMap.GetArray();
protoArray["19"]["m_columns"].Add("id");
protoArray["19"]["m_columns"].Add("record");
protoArray["19"]["m_columns"].Add("committee_member");
protoArray["19"]["m_columns"].Add("date_voted");
protoArray["19"]["m_columns"].Add("vote");
protoArray["19"]["m_columns"].Add("comment");
obj = new SQLTable(protoArray["19"]);

protoArray["18"]["m_table"] = obj;
protoArray["18"]["m_sql"] = "dbo.[_ABCVotes]";
protoArray["18"]["m_alias"] = "";
protoArray["18"]["m_srcTableName"] = "dbo._ABCVotes";
protoArray["20"] = SettingsMap.GetArray();
protoArray["20"]["m_sql"] = "";
protoArray["20"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["20"]["m_column"] = obj;
protoArray["20"]["m_contained"] = SettingsMap.GetArray();
protoArray["20"]["m_strCase"] = "";
protoArray["20"]["m_havingmode"] = false;
protoArray["20"]["m_inBrackets"] = false;
protoArray["20"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["20"]);

protoArray["18"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["18"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["0"]["m_srcTableName"] = "dbo._ABCVotes";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["dbo__ABCVotes"] = obj;

				
		
			tdataArray["dbo__ABCVotes"][".sqlquery"] = queryData_Array["dbo__ABCVotes"];
			GlobalVars.tableEvents["dbo._ABCVotes"] = new eventclass_dbo__ABCVotes();
			tdataArray["dbo__ABCVotes"][".hasEvents"] = true;
			GlobalVars.tables_data["dbo__ABCVotes"] = tdataArray["dbo__ABCVotes"];
		}
	}

}
