using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public partial class CommonFunctions
	{
		public static XVar getMenuNodes_main(dynamic _param_menuNodesObject)
		{
			#region pass-by-value parameters
			dynamic menuNodesObject = XVar.Clone(_param_menuNodesObject);
			#endregion

			dynamic menuNode = XVar.Array();
			menuNodesObject.menuNodes.InitAndSetArrayItem(XVar.Array(), "main");
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("1", "id");
			menuNode.InitAndSetArrayItem("ABC Maintenance", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo._ABCReports", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("0", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem("List", "pageType");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("ABC Maintenance", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "main", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("2", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("ABC_Voting_Batch_Create", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("0", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem("List", "pageType");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("ABC Voting Batch Create", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "main", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("3", "id");
			menuNode.InitAndSetArrayItem("ABC Security", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo._ABCSecurity", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("0", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem("List", "pageType");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("ABC Security", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "main", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("4", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("ABC_Voting_Recirculated", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("0", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem("List", "pageType");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("ABC Voting Recirculated", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "main", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("5", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("ABC_Voting_Submitted", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("0", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem("List", "pageType");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("ABC Voting Submitted", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "main", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("6", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("ABC_Voting_My_Voting", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("0", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem("List", "pageType");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("ABC Voting My Voting", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "main", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("7", "id");
			menuNode.InitAndSetArrayItem("ABC Reports Vote Count", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.vwABCReportsVoteCount", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("0", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem("List", "pageType");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("ABC Reports Vote Count", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "main", null);
			return null;
		}
	}
}
