using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public partial class CommonFunctions
	{
		public static XVar getMenuNodes_welcome_page(dynamic _param_menuNodesObject)
		{
			#region pass-by-value parameters
			dynamic menuNodesObject = XVar.Clone(_param_menuNodesObject);
			#endregion

			dynamic menuNode = XVar.Array();
			menuNodesObject.menuNodes.InitAndSetArrayItem(XVar.Array(), "welcome_page");
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("1", "id");
			menuNode.InitAndSetArrayItem("ABCVote2016", "name");
			menuNode.InitAndSetArrayItem("", "href");
			menuNode.InitAndSetArrayItem("Group", "type");
			menuNode.InitAndSetArrayItem("", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("0", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("None", "linkType");
			menuNode.InitAndSetArrayItem("List", "pageType");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("ABCVote2016", "title");
			menuNode.InitAndSetArrayItem("Project description", "comments");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "welcome_page", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("2", "id");
			menuNode.InitAndSetArrayItem("ABCReports", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo._ABCReports", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("1", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem("List", "pageType");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("glyphicon-tree-conifer", "icon");
			menuNode.InitAndSetArrayItem("2", "iconType");
			menuNode.InitAndSetArrayItem(MVCFunctions.Concat("#", "E8926F"), "color");
			menuNode.InitAndSetArrayItem("ABCReports", "title");
			menuNode.InitAndSetArrayItem("Change this text on the Welcome page in the Visual Editor.", "comments");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "welcome_page", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("3", "id");
			menuNode.InitAndSetArrayItem("ABCVotes", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo._ABCVotes", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("1", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem("List", "pageType");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("glyphicon-calendar", "icon");
			menuNode.InitAndSetArrayItem("2", "iconType");
			menuNode.InitAndSetArrayItem(MVCFunctions.Concat("#", "BC8F8F"), "color");
			menuNode.InitAndSetArrayItem("ABCVotes", "title");
			menuNode.InitAndSetArrayItem("ABCVotes description", "comments");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "welcome_page", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("4", "id");
			menuNode.InitAndSetArrayItem("ABCSecurity", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo._ABCSecurity", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("1", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem("List", "pageType");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("glyphicon-leaf", "icon");
			menuNode.InitAndSetArrayItem("2", "iconType");
			menuNode.InitAndSetArrayItem(MVCFunctions.Concat("#", "5F9EA0"), "color");
			menuNode.InitAndSetArrayItem("ABCSecurity", "title");
			menuNode.InitAndSetArrayItem("ABCSecurity description", "comments");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "welcome_page", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("5", "id");
			menuNode.InitAndSetArrayItem("ABC Voting Submitted", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("ABC_Voting_Submitted", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("1", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem("List", "pageType");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("glyphicon-calendar", "icon");
			menuNode.InitAndSetArrayItem("2", "iconType");
			menuNode.InitAndSetArrayItem(MVCFunctions.Concat("#", "DB7093"), "color");
			menuNode.InitAndSetArrayItem("ABC Voting Submitted", "title");
			menuNode.InitAndSetArrayItem("ABC Voting Submitted description", "comments");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "welcome_page", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("6", "id");
			menuNode.InitAndSetArrayItem("ABC Voting Recirculated", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("ABC_Voting_Recirculated", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("1", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem("List", "pageType");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("glyphicon-leaf", "icon");
			menuNode.InitAndSetArrayItem("2", "iconType");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("ABC Voting Recirculated", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "welcome_page", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("7", "id");
			menuNode.InitAndSetArrayItem("ABC Voting My Voting", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("ABC_Voting_My_Voting", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("1", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem("List", "pageType");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("glyphicon-hand-right", "icon");
			menuNode.InitAndSetArrayItem("2", "iconType");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("ABC Voting My Voting", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "welcome_page", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("8", "id");
			menuNode.InitAndSetArrayItem("ABC Voting Batch Create", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("ABC_Voting_Batch_Create", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("1", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem("List", "pageType");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("ABC Voting Batch Create", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "welcome_page", null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("9", "id");
			menuNode.InitAndSetArrayItem("Vw ABCReports Vote Count", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.vwABCReportsVoteCount", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("1", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem("List", "pageType");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Vw ABCReports Vote Count", "title");
			menuNodesObject.menuNodes.InitAndSetArrayItem(menuNode, "welcome_page", null);
			return null;
		}
	}
}
